// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateTimeSlotRequestType.
const (
	CreateTimeSlotRequestTypeRecurring CreateTimeSlotRequestType = "recurring"
	CreateTimeSlotRequestTypeSingle    CreateTimeSlotRequestType = "single"
)

// Defines values for RecurrenceEndType.
const (
	Date  RecurrenceEndType = "date"
	Never RecurrenceEndType = "never"
)

// Defines values for RecurrenceFrequency.
const (
	Daily   RecurrenceFrequency = "daily"
	Monthly RecurrenceFrequency = "monthly"
	Weekly  RecurrenceFrequency = "weekly"
)

// Defines values for TimeSlotStatus.
const (
	TimeSlotStatusActive   TimeSlotStatus = "active"
	TimeSlotStatusArchived TimeSlotStatus = "archived"
)

// Defines values for TimeSlotType.
const (
	TimeSlotTypeRecurring TimeSlotType = "recurring"
	TimeSlotTypeSingle    TimeSlotType = "single"
)

// Defines values for GetEventsParamsStatus.
const (
	Past     GetEventsParamsStatus = "past"
	Upcoming GetEventsParamsStatus = "upcoming"
)

// Defines values for GetTimeSlotsParamsStatus.
const (
	GetTimeSlotsParamsStatusActive   GetTimeSlotsParamsStatus = "active"
	GetTimeSlotsParamsStatusArchived GetTimeSlotsParamsStatus = "archived"
)

// AddParticipantToEventRequest defines model for AddParticipantToEventRequest.
type AddParticipantToEventRequest struct {
	ParticipantId int64 `json:"participant_id"`
	VolunteerId   int64 `json:"volunteer_id"`
}

// BlockClientRequest defines model for BlockClientRequest.
type BlockClientRequest struct {
	BlockReason *string `json:"block_reason,omitempty"`
	IsBlocked   bool    `json:"is_blocked"`
}

// Client defines model for Client.
type Client struct {
	BirthDate     *time.Time `json:"birth_date,omitempty"`
	BlockedAt     *time.Time `json:"blocked_at,omitempty"`
	BlockedReason *string    `json:"blocked_reason,omitempty"`
	FirstName     string     `json:"first_name"`
	Gender        *int32     `json:"gender,omitempty"`
	Id            int64      `json:"id"`
	IsBlocked     *bool      `json:"is_blocked,omitempty"`
	IsHomeless    *bool      `json:"is_homeless,omitempty"`
	IsNew         bool       `json:"is_new"`
	LastName      string     `json:"last_name"`
	MiddleName    string     `json:"middle_name"`
	PhotoName     *string    `json:"photo_name,omitempty"`
}

// CreateClientRequest defines model for CreateClientRequest.
type CreateClientRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// CreateLocationRequest defines model for CreateLocationRequest.
type CreateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// CreateTimeSlotRequest defines model for CreateTimeSlotRequest.
type CreateTimeSlotRequest struct {
	Capacity   int32                     `json:"capacity"`
	EndDate    time.Time                 `json:"endDate"`
	LocationId int64                     `json:"locationId"`
	Recurrence *Recurrence               `json:"recurrence,omitempty"`
	Services   []TimeSlotService         `json:"services"`
	StartDate  time.Time                 `json:"startDate"`
	Title      string                    `json:"title"`
	Type       CreateTimeSlotRequestType `json:"type"`
}

// CreateTimeSlotRequestType defines model for CreateTimeSlotRequest.Type.
type CreateTimeSlotRequestType string

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Capacity          int32     `json:"capacity"`
	Datetime          time.Time `json:"datetime"`
	Id                int64     `json:"id"`
	ParticipantsCount int32     `json:"participantsCount"`
	ServiceName       string    `json:"serviceName"`
	ServiceTypeId     int64     `json:"serviceTypeId"`
	TimeSlotServiceId int64     `json:"timeSlotServiceId"`
}

// GetAvailableServicesResponse defines model for GetAvailableServicesResponse.
type GetAvailableServicesResponse struct {
	Services []ServiceType `json:"services"`
}

// GetClientsResponse defines model for GetClientsResponse.
type GetClientsResponse struct {
	Clients    []Client `json:"clients"`
	Page       int32    `json:"page"`
	PerPage    int32    `json:"per_page"`
	Total      int32    `json:"total"`
	TotalPages int32    `json:"total_pages"`
}

// GetEventsResponse defines model for GetEventsResponse.
type GetEventsResponse struct {
	Items      []Event `json:"items"`
	Page       int32   `json:"page"`
	PerPage    int32   `json:"per_page"`
	Total      int32   `json:"total"`
	TotalPages int32   `json:"total_pages"`
}

// GetParticipantsResponse defines model for GetParticipantsResponse.
type GetParticipantsResponse struct {
	Page         int32         `json:"page"`
	Participants []Participant `json:"participants"`
	PerPage      int32         `json:"per_page"`
	Total        int32         `json:"total"`
	TotalPages   int32         `json:"total_pages"`
}

// GetServicesResponse defines model for GetServicesResponse.
type GetServicesResponse struct {
	Items      []ServiceType `json:"items"`
	Page       int32         `json:"page"`
	PerPage    int32         `json:"per_page"`
	Total      int32         `json:"total"`
	TotalPages int32         `json:"total_pages"`
}

// Location defines model for Location.
type Location struct {
	Address *string `json:"address,omitempty"`
	Id      int64   `json:"id"`
	Name    string  `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// Participant defines model for Participant.
type Participant struct {
	BirthDate            *time.Time `json:"birth_date,omitempty"`
	FirstName            string     `json:"first_name"`
	Id                   int64      `json:"id"`
	LastName             string     `json:"last_name"`
	MiddleName           string     `json:"middle_name"`
	PhotoName            *string    `json:"photo_name,omitempty"`
	VolounteerFirstName  string     `json:"volounteer_first_name"`
	VolounteerLastName   string     `json:"volounteer_last_name"`
	VolounteerMiddleName string     `json:"volounteer_middle_name"`
	VolunteerTg          int64      `json:"volunteer_tg"`
	VolunteerTgLogin     string     `json:"volunteer_tg_login"`
}

// Recurrence defines model for Recurrence.
type Recurrence struct {
	EndType   RecurrenceEndType   `json:"endType"`
	EndValue  *time.Time          `json:"endValue"`
	Frequency RecurrenceFrequency `json:"frequency"`
	Interval  int32               `json:"interval"`
}

// RecurrenceEndType defines model for Recurrence.EndType.
type RecurrenceEndType string

// RecurrenceFrequency defines model for Recurrence.Frequency.
type RecurrenceFrequency string

// ServiceType defines model for ServiceType.
type ServiceType struct {
	Id                    int64  `json:"id"`
	MinPeriodDays         int32  `json:"min_period_days"`
	Name                  string `json:"name"`
	RegistrationAvailable bool   `json:"registration_available"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	Capacity   int32             `json:"capacity"`
	EndDate    time.Time         `json:"endDate"`
	Id         int64             `json:"id"`
	LocationId int64             `json:"locationId"`
	Recurrence *Recurrence       `json:"recurrence,omitempty"`
	Services   []TimeSlotService `json:"services"`
	StartDate  time.Time         `json:"startDate"`
	Status     TimeSlotStatus    `json:"status"`
	Title      string            `json:"title"`
	Type       TimeSlotType      `json:"type"`
}

// TimeSlotStatus defines model for TimeSlot.Status.
type TimeSlotStatus string

// TimeSlotType defines model for TimeSlot.Type.
type TimeSlotType string

// TimeSlotService defines model for TimeSlotService.
type TimeSlotService struct {
	BookingWindow int32     `json:"bookingWindow"`
	Capacity      int32     `json:"capacity"`
	Id            *int64    `json:"id,omitempty"`
	ServiceTypeId int64     `json:"serviceTypeId"`
	Time          time.Time `json:"time"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Capacity int32     `json:"capacity"`
	Datetime time.Time `json:"datetime"`
}

// UpdateLocationRequest defines model for UpdateLocationRequest.
type UpdateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// UpdateServiceRegistrationRequest defines model for UpdateServiceRegistrationRequest.
type UpdateServiceRegistrationRequest struct {
	MinPeriodDays         int32 `json:"min_period_days"`
	RegistrationAvailable bool  `json:"registration_available"`
}

// UpdateVolunteerRequest defines model for UpdateVolunteerRequest.
type UpdateVolunteerRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// Volunteer defines model for Volunteer.
type Volunteer struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
	TgId       int64  `json:"tg_id"`
	TgLogin    string `json:"tg_login"`
}

// GetClientsParams defines parameters for GetClients.
type GetClientsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int   `form:"per_page" json:"per_page"`
}

// GetClientsIdEventsParams defines parameters for GetClientsIdEvents.
type GetClientsIdEventsParams struct {
	HistoryLimit *int32 `form:"history_limit,omitempty" json:"history_limit,omitempty"`
	Page         *int32 `form:"page,omitempty" json:"page,omitempty"`
	PerPage      *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetClientsIdServicesParams defines parameters for GetClientsIdServices.
type GetClientsIdServicesParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	Page          int32                  `form:"page" json:"page"`
	PerPage       int32                  `form:"per_page" json:"per_page"`
	ParticipantId *int64                 `form:"participant_id,omitempty" json:"participant_id,omitempty"`
	Status        *GetEventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	LocationId    *int64                 `form:"location_id,omitempty" json:"location_id,omitempty"`
	ServiceId     *int64                 `form:"service_id,omitempty" json:"service_id,omitempty"`
	FromDate      *time.Time             `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate        *time.Time             `form:"to_date,omitempty" json:"to_date,omitempty"`
}

// GetEventsParamsStatus defines parameters for GetEvents.
type GetEventsParamsStatus string

// GetEventsServicesIdParams defines parameters for GetEventsServicesId.
type GetEventsServicesIdParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsIdParticipantsParams defines parameters for GetEventsIdParticipants.
type GetEventsIdParticipantsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	Page                  int32 `form:"page" json:"page"`
	PerPage               int32 `form:"per_page" json:"per_page"`
	RegistrationAvailable *bool `form:"registration_available,omitempty" json:"registration_available,omitempty"`
}

// GetTimeSlotsParams defines parameters for GetTimeSlots.
type GetTimeSlotsParams struct {
	Status    *GetTimeSlotsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	StartDate *time.Time                `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time                `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetTimeSlotsParamsStatus defines parameters for GetTimeSlots.
type GetTimeSlotsParamsStatus string

// PostClientsJSONRequestBody defines body for PostClients for application/json ContentType.
type PostClientsJSONRequestBody = CreateClientRequest

// PutClientsIdJSONRequestBody defines body for PutClientsId for application/json ContentType.
type PutClientsIdJSONRequestBody = BlockClientRequest

// PutEventsIdJSONRequestBody defines body for PutEventsId for application/json ContentType.
type PutEventsIdJSONRequestBody = UpdateEventRequest

// PutEventsIdParticipantsJSONRequestBody defines body for PutEventsIdParticipants for application/json ContentType.
type PutEventsIdParticipantsJSONRequestBody = AddParticipantToEventRequest

// PostLocationsJSONRequestBody defines body for PostLocations for application/json ContentType.
type PostLocationsJSONRequestBody = CreateLocationRequest

// PutLocationsIdJSONRequestBody defines body for PutLocationsId for application/json ContentType.
type PutLocationsIdJSONRequestBody = UpdateLocationRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PutServicesIdJSONRequestBody defines body for PutServicesId for application/json ContentType.
type PutServicesIdJSONRequestBody = UpdateServiceRegistrationRequest

// PostTimeSlotsJSONRequestBody defines body for PostTimeSlots for application/json ContentType.
type PostTimeSlotsJSONRequestBody = CreateTimeSlotRequest

// PutTimeSlotsIdJSONRequestBody defines body for PutTimeSlotsId for application/json ContentType.
type PutTimeSlotsIdJSONRequestBody = TimeSlot

// PostVolunteersJSONRequestBody defines body for PostVolunteers for application/json ContentType.
type PostVolunteersJSONRequestBody = Volunteer

// PutVolunteersTgIdJSONRequestBody defines body for PutVolunteersTgId for application/json ContentType.
type PutVolunteersTgIdJSONRequestBody = UpdateVolunteerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка живых клиентов
	// (GET /clients)
	GetClients(ctx echo.Context, params GetClientsParams) error
	// Создание нового клиента
	// (POST /clients)
	PostClients(ctx echo.Context) error
	// Получение клиента по идентификатору
	// (GET /clients/{id})
	GetClientsId(ctx echo.Context, id int64) error
	// Блокировка/Разблокировка клиента
	// (PUT /clients/{id})
	PutClientsId(ctx echo.Context, id int64) error
	// Получение списка событий клиента
	// (GET /clients/{id}/events)
	GetClientsIdEvents(ctx echo.Context, id int64, params GetClientsIdEventsParams) error
	// Получение списка услуг доступных клиенту
	// (GET /clients/{id}/services)
	GetClientsIdServices(ctx echo.Context, id int64, params GetClientsIdServicesParams) error
	// Получение списка событий
	// (GET /events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// Получение списка событий по типу услуги
	// (GET /events/services/{id})
	GetEventsServicesId(ctx echo.Context, id int64, params GetEventsServicesIdParams) error
	// Удаление события по идентификатору
	// (DELETE /events/{id})
	DeleteEventsId(ctx echo.Context, id int64) error
	// Получение события по идентификатору
	// (GET /events/{id})
	GetEventsId(ctx echo.Context, id int64) error
	// Обновление события по идентификатору
	// (PUT /events/{id})
	PutEventsId(ctx echo.Context, id int64) error
	// Получение списка участников события
	// (GET /events/{id}/participants)
	GetEventsIdParticipants(ctx echo.Context, id int64, params GetEventsIdParticipantsParams) error
	// Добавление участника к событию
	// (PUT /events/{id}/participants)
	PutEventsIdParticipants(ctx echo.Context, id int64) error
	// Удаление участника из события
	// (DELETE /events/{id}/participants/{participant_id})
	DeleteEventsIdParticipantsParticipantId(ctx echo.Context, id int64, participantId int64) error
	// Получение списка локаций
	// (GET /locations)
	GetLocations(ctx echo.Context) error
	// Создание новой локации
	// (POST /locations)
	PostLocations(ctx echo.Context) error
	// Удаление локации по идентификатору
	// (DELETE /locations/{id})
	DeleteLocationsId(ctx echo.Context, id int64) error
	// Обновление локации по идентификатору
	// (PUT /locations/{id})
	PutLocationsId(ctx echo.Context, id int64) error
	// Вход в систему
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Получение списка услуг
	// (GET /services)
	GetServices(ctx echo.Context, params GetServicesParams) error
	// Получение информации об услуге по идентификатору
	// (GET /services/{id})
	GetServicesId(ctx echo.Context, id int64) error
	// Обновление информации об услуге по идентификатору
	// (PUT /services/{id})
	PutServicesId(ctx echo.Context, id int64) error
	// Получение списка временных слотов
	// (GET /timeSlots)
	GetTimeSlots(ctx echo.Context, params GetTimeSlotsParams) error
	// Создание нового временного слота
	// (POST /timeSlots)
	PostTimeSlots(ctx echo.Context) error
	// Удаление временного слота
	// (DELETE /timeSlots/{id})
	DeleteTimeSlotsId(ctx echo.Context, id int64) error
	// Получение временного слота по идентификатору
	// (GET /timeSlots/{id})
	GetTimeSlotsId(ctx echo.Context, id int64) error
	// Обновление временного слота
	// (PUT /timeSlots/{id})
	PutTimeSlotsId(ctx echo.Context, id int64) error
	// Активация временного слота
	// (PATCH /timeSlots/{id}/activate)
	PatchTimeSlotsIdActivate(ctx echo.Context, id int64) error
	// Архивация временного слота
	// (PATCH /timeSlots/{id}/archive)
	PatchTimeSlotsIdArchive(ctx echo.Context, id int64) error
	// Создание нового волонтера
	// (POST /volunteers)
	PostVolunteers(ctx echo.Context) error
	// Получение волонтера по идентификатору
	// (GET /volunteers/{tg_id})
	GetVolunteersTgId(ctx echo.Context, tgId int64) error
	// Обновление волонтера
	// (PUT /volunteers/{tg_id})
	PutVolunteersTgId(ctx echo.Context, tgId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClients converts echo context to params.
func (w *ServerInterfaceWrapper) GetClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClients(ctx, params)
	return err
}

// PostClients converts echo context to params.
func (w *ServerInterfaceWrapper) PostClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostClients(ctx)
	return err
}

// GetClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsId(ctx, id)
	return err
}

// PutClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutClientsId(ctx, id)
	return err
}

// GetClientsIdEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdEvents(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdEventsParams
	// ------------- Optional query parameter "history_limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "history_limit", ctx.QueryParams(), &params.HistoryLimit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter history_limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdEvents(ctx, id, params)
	return err
}

// GetClientsIdServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdServices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdServices(ctx, id, params)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "participant_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "participant_id", ctx.QueryParams(), &params.ParticipantId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter participant_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "location_id", ctx.QueryParams(), &params.LocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter location_id: %s", err))
	}

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", ctx.QueryParams(), &params.ServiceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_id: %s", err))
	}

	// ------------- Optional query parameter "from_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_date", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from_date: %s", err))
	}

	// ------------- Optional query parameter "to_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_date", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to_date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetEventsServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsServicesIdParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsServicesId(ctx, id, params)
	return err
}

// DeleteEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventsId(ctx, id)
	return err
}

// GetEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsId(ctx, id)
	return err
}

// PutEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsId(ctx, id)
	return err
}

// GetEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsIdParticipantsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsIdParticipants(ctx, id, params)
	return err
}

// PutEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsIdParticipants(ctx, id)
	return err
}

// DeleteEventsIdParticipantsParticipantId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventsIdParticipantsParticipantId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "participant_id" -------------
	var participantId int64

	err = runtime.BindStyledParameterWithOptions("simple", "participant_id", ctx.Param("participant_id"), &participantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter participant_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventsIdParticipantsParticipantId(ctx, id, participantId)
	return err
}

// GetLocations converts echo context to params.
func (w *ServerInterfaceWrapper) GetLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLocations(ctx)
	return err
}

// PostLocations converts echo context to params.
func (w *ServerInterfaceWrapper) PostLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLocations(ctx)
	return err
}

// DeleteLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLocationsId(ctx, id)
	return err
}

// PutLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutLocationsId(ctx, id)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// GetServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetServices(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "registration_available" -------------

	err = runtime.BindQueryParameter("form", true, false, "registration_available", ctx.QueryParams(), &params.RegistrationAvailable)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter registration_available: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServices(ctx, params)
	return err
}

// GetServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServicesId(ctx, id)
	return err
}

// PutServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) PutServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutServicesId(ctx, id)
	return err
}

// GetTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimeSlotsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlots(ctx, params)
	return err
}

// PostTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) PostTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTimeSlots(ctx)
	return err
}

// DeleteTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTimeSlotsId(ctx, id)
	return err
}

// GetTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlotsId(ctx, id)
	return err
}

// PutTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTimeSlotsId(ctx, id)
	return err
}

// PatchTimeSlotsIdActivate converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdActivate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdActivate(ctx, id)
	return err
}

// PatchTimeSlotsIdArchive converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdArchive(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdArchive(ctx, id)
	return err
}

// PostVolunteers converts echo context to params.
func (w *ServerInterfaceWrapper) PostVolunteers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVolunteers(ctx)
	return err
}

// GetVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) GetVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVolunteersTgId(ctx, tgId)
	return err
}

// PutVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) PutVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutVolunteersTgId(ctx, tgId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/clients", wrapper.GetClients)
	router.POST(baseURL+"/clients", wrapper.PostClients)
	router.GET(baseURL+"/clients/:id", wrapper.GetClientsId)
	router.PUT(baseURL+"/clients/:id", wrapper.PutClientsId)
	router.GET(baseURL+"/clients/:id/events", wrapper.GetClientsIdEvents)
	router.GET(baseURL+"/clients/:id/services", wrapper.GetClientsIdServices)
	router.GET(baseURL+"/events", wrapper.GetEvents)
	router.GET(baseURL+"/events/services/:id", wrapper.GetEventsServicesId)
	router.DELETE(baseURL+"/events/:id", wrapper.DeleteEventsId)
	router.GET(baseURL+"/events/:id", wrapper.GetEventsId)
	router.PUT(baseURL+"/events/:id", wrapper.PutEventsId)
	router.GET(baseURL+"/events/:id/participants", wrapper.GetEventsIdParticipants)
	router.PUT(baseURL+"/events/:id/participants", wrapper.PutEventsIdParticipants)
	router.DELETE(baseURL+"/events/:id/participants/:participant_id", wrapper.DeleteEventsIdParticipantsParticipantId)
	router.GET(baseURL+"/locations", wrapper.GetLocations)
	router.POST(baseURL+"/locations", wrapper.PostLocations)
	router.DELETE(baseURL+"/locations/:id", wrapper.DeleteLocationsId)
	router.PUT(baseURL+"/locations/:id", wrapper.PutLocationsId)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.GET(baseURL+"/services", wrapper.GetServices)
	router.GET(baseURL+"/services/:id", wrapper.GetServicesId)
	router.PUT(baseURL+"/services/:id", wrapper.PutServicesId)
	router.GET(baseURL+"/timeSlots", wrapper.GetTimeSlots)
	router.POST(baseURL+"/timeSlots", wrapper.PostTimeSlots)
	router.DELETE(baseURL+"/timeSlots/:id", wrapper.DeleteTimeSlotsId)
	router.GET(baseURL+"/timeSlots/:id", wrapper.GetTimeSlotsId)
	router.PUT(baseURL+"/timeSlots/:id", wrapper.PutTimeSlotsId)
	router.PATCH(baseURL+"/timeSlots/:id/activate", wrapper.PatchTimeSlotsIdActivate)
	router.PATCH(baseURL+"/timeSlots/:id/archive", wrapper.PatchTimeSlotsIdArchive)
	router.POST(baseURL+"/volunteers", wrapper.PostVolunteers)
	router.GET(baseURL+"/volunteers/:tg_id", wrapper.GetVolunteersTgId)
	router.PUT(baseURL+"/volunteers/:tg_id", wrapper.PutVolunteersTgId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdb4/bthn/KoI2oG+UnO5PstTvrmlXXFa0QZKmw7KDoVg8m40suRLtxDsYuNw1a4cE",
	"va3bi2JD23X9As41bpxzzvkK1DcaSOoPJVGy/O/gJHwTXCyKfEg+v9/z8HlIal+tOc2WYwMbeWplX/Vq",
	"DdA06J/bpnndcBGswZZho1vOBx1goxvgizbwEHkOHhjNlgXIn624XBWaamVdUzuO1bYRAC79YaOnqS3X",
	"aQEXQeCJXtlX9xy3aSC1okIbXd5SNRV1W4D9F9SBq/bSlZZ4paepLviiDV1gqpU76UZTFe5G7zt3Pwc1",
	"RFp8z3Jq965aMLfrd0mBqgsMz7HViopICU2FXpU+IM0itw0y3U++th827CEX2nXSMF9D9Piu41jAsDP9",
	"4gqLOsHkTwm+B10PVW2jScri7/AJ7uMzIjqbP+hVG04TWMDzWBc01TKyL+AxPlE1tQlN0wKih3jof6Vq",
	"aqvhICd8Tv9z8fMW7WhqXKCLGlXTQCAxv+SHCwg2QTzH8VAFXa8aaPp3CmaAHyDB4zqwTeCmtXBzQ6i4",
	"pTW8eNpT05JTwAb3xc+4CRR0KDGHguf8FGYepxWSgIsbwGTtvCSRxELFdYGBQBH88rR4dl3NqOQEPZhn",
	"UFOjVmrA8sfpI6dmIOjY4pEyTNOlWqP6R3h0UcHf0y73/WNNufw7VVPDAaG/+4/xC8V/5B/gPn6ZHZOo",
	"MkGXy/U16FdYUX6vbsEmuGk5OfNfM1pGDaKuWlnXdU0Ftvk+5Q51Q9+4dEHfvLCh31p/t6LrFV3/ExnH",
	"YIx2GMu5oNZ2XWDXaGXANm8xISgB0epuG1Y7rm8rXd8e6ROwa121ot4H4J7VJRptI+B2DEutrPc01QNu",
	"B9bIuN3ZJ2i8B+36Z9A2nftqZVPXuC5s6VFpIkcgI6WwZIeuhAL0tAlVXs5WuZFT5WZQ5a6meshwkWAg",
	"r8QdRxBZVF3+hwf+Q/9Qwa+o3hzisX+AB/gMD/Egpjg20CGTJHQpFrYUlUZTXIrqNfXBhY5hQWZR7hB3",
	"xzYh0QC1Elal/Lmt65tAiXutqW6b9i4s0Wx7SLkLFGMPAZcr2NvtJXWqFMknte63LthTK+pv1mJPbC1w",
	"w9ZuxCUTmrSvQgSa3qTXQ+zcZC+SOgJpDNc1urTOeKrnH9CosnBIbed+PJjx03A4oa2gBlD22qjtAqrM",
	"BbXVlHDqC2q8C/YcF0Ql6fwEqiqgKvYDAX67SUjJg3bdovVH6rqrTSAyVntQKqEMHA75cY5VmJtREf99",
	"4LqOm+I7EyADWoTF8Y94jEd4oLxDqPQdBY/xU/8YP8d9/xAP8Mh/Qoyagp/hkX+skN8pQkf4jKHTPyZG",
	"BnieUac4/sH/Gg/xU3yK+wo1iSM8xM9w3/8rHuJhFraRJCKrF1Y7yQqEBYXd72Sd1pgrNnSNamlMZVsB",
	"S+kcPQfOLOf3e1edNql2XWc0yMGD8u289BTLVNYVLe0bCnpRSqRAyT7O81FS9qGULIKhm345lq0kAZlo",
	"KNMiasy/5PslGh2RUn0I0HbHgJZx1wJBs94N4LUc22Mr2cTcT024N2M5s2Sb6n0h9j8EiLm9Cel4JLCn",
	"lIInLOXm8IV3ybgSIBMQAbca/Idgx0HUwdHDv+kzj/yShVAoa8lRDNarAmvVClilhNbH4pYqHvSnfNmw",
	"vyXeSE18OBxho0G3OJGTTeToB+XHPPUIxvnOzJQp5sbZqtsQVrexIO2KVKqUbjGr8qaqFhuCORWLi/oV",
	"cOM048VVWHqiOCmE07Wyc5Do7ZxTMdlETaf9hfZJYiAY+DCQMimC8qN/gIf4JR74B/iMRVLWNzZjDg3N",
	"6j/xCPfxCT6bI6pS2kucIkCXG0/6yKnDnDCSRR4RnTGb0Kaj63n3HddUK/GfmY4FL4mCitHrkyRmdXBv",
	"FAguNInIuQfoqr97rXH3wxr8BF7b+fQvO+sfwx1vx75xqXZ15/LOvdYfb1+99m62C8Hbk6RkxUSi8XyW",
	"SiFwMe88M7o0Fy83NE+TI06QHclrnitSIAJXaqI0cUYG1VOJJFSvhtoHO4ZdJf84ncXkECYEeUujb4kh",
	"9twJKS5ZLFHe1IiLcjMzZb4unrtFpg4SIgmbyxu03J7njJ0I0TeSweMY0BPiyFuzxZGTSh61EUevbNAB",
	"brBuFsSteDFyYGG3LboyDjN+WZjEYsbtmgak4kZyNx0bNayuUIa4TwLL3oQ2bJJK1yda+VgSrk4tGhbR",
	"fPHOT2q1xFi0Ce1qC7jQMaum0fUSNvw7/yGLcOMBfuY/oTHCOvSQSz2FqhEGFXLyvaUJJCNDKZcpF7R5",
	"Qk5OKUcOQlam3GpFox7GoHMjeZfSeZvQ/q3rmVVpKn1TPrWyMSG1IrK54Zo1WvsWtrA5IdPCtbApbiGb",
	"eBFJ5SEDtYkTatQQ7AA+FfOzfxjkXs78Y/9Y8R/ikX+Ef8VPcZ8zeizIfb55mKls6NuUT+nFMxozajS1",
	"hltrwE5iWweXvVhqXoMSwHzJDdavCVmO9JimfOPFgjrrKybrL6X5UwKltN7PGocvq2ni+HMUU+fmMzkq",
	"QSuiyfu0Rdor2Bk2XbjwvJMv6cCsIPeQ3+s3bbsF61UAwxucgRd3UOQsTeUSzebpzOzQzOXEsLG5Ha4v",
	"ptuL9AZuOIpGYunbsTQV1cM9pVwAAAEPVaP13rmOYSRROYIuvfBltXJvaLPOD7UltbYLUfcm8VzYkLwH",
	"DBe4223UoIaP/u/3YQeufXaLGGpamoCIPo071ECopfZ6dP2257D0v1dzYSvYqrF9fSfcaeAf4VeUx07w",
	"KNxpoOAT6pi+DJzTx/glHlL3FI/9Q8J5eKgp5H/4lO048I9pEVLqKHBjf2HlFHyi4D5+Rv6mtT+kXm/f",
	"P8RDfEI154WCX1ElGuARHio3DWgj5YM6NKHDucv8z8q22YS2sn19R9XUDnA91q31i/pFncyi0wK20YJq",
	"Rd2kP2lqy0ANOqxrXHazDignEEWMPFgulcuy1EYTIOCyNQvV5S/awO3GFiEIUseqwdbizAdlQ79ntC1E",
	"ITHlEjqnxTg0nt9qprJdUppFWmnnN3SdmmzHRsHGDaPVsiAzkmufB9ts4wpLedyCPHg2r04sf0Id8c90",
	"tT7wvw5i7lTNTvDAPySvb00paWE+kW7SEckweUPNlr6+fDm2azXgeYoJbAhoaP7SefR+x0bAtQ1LIV4m",
	"cBUQFNRUr91sGm432sHkH/lfhfsFFTptQ/8hG7RfCaL9x/4jBZ/S0RvgM/8wsBvIqHt8Nn2X2ADHEwDw",
	"uuNxCHSZ7X7PMbsLGwbRPuVejxF8AiGLm+9wj4RU/tdU+X/CY/ycDEmg+oHPM8a/4HFS3/tCbe9pkelZ",
	"24dmr4T9ocu8lAUCD1qWYwK1smdYHtCYfSDGLTYP1CvJNwxlVraoy/ZrQuoozm06JDAWDowtfescev/v",
	"WK2JwlOt7+MX+Bn5bdWNUxKUdMO7QieP/TL0v8RD6r/SPfD+UZ6RaotsVHs1Qbp4Wyk4USc0lZIRJCOs",
	"FiP8I1igDv0DaqpPcX8N/xf38XP8NPtoFhu+Bjoll5I7Jtv+uSJckbOwbEAPOW63asEmRKpwDbupldng",
	"VbhSLrkynmE1LKj5Upmal+nfZHf+SmKTxLbMdbj/kJ4tekwjbC9m4jU+0zqR2cJNr6vNbSsapota3dBF",
	"zRoPgmZ1fYIQS+aw/FM4ks4knS2VzqKEgoKf4THNHxzhV0SzUpHGnCUcYbfJjlqef/Y2ckkuhaauY5mC",
	"p/PqjDedRHWFu2DarZrTZGeYW4aHhFtgxJWG+14WJyUjvYXVt+c6zWqw2VRQXeEWCHGNyJmxPun7yvj3",
	"wp1OjocD5uVpOHIvJwbCmfaELsfKhNqkiymp4u30Kz92kLLntG3ztV4Rv8Jjhf79yj/iN6wMJ/BWSFcm",
	"sADbMZxkrPfp70yP35jkXeqKhTbVu5wNfOmNTRLBEsHlEPwzTa2PePxGkPWPp0reRcjVJvgVb0V+PbhA",
	"QUJRQnEeY7oAMOYl0lcRjIvPowuOXvSSW4qDXfeSCSQTrAgT/ICfBtvcFmuYUy71WvrCmUlm+3ryyhYZ",
	"EnhTQwLCq40kg61iwuknbok9yKac8Hj6tM9XuO8/9A/p01NCQynymc3NWEHyWJLLUfhFAOEmvq3FRAai",
	"E2aJaylkoOD19Um29HfPp0VgO+16Q4mO9q6UP/Qvwj78UTlCWmme6iv4NElU30zrA63tJ1OtUwQdeXbj",
	"/l6l1EmJdjOZ5iWHWyTvyWzofOFKAQsM8fMSDgvhgXC/QuHi56Oo0Hkc5IzuVOzR9cAOe4dd8CpPc74N",
	"pzm5092JhH6srMVHOJP6uqxDnOlbPUrF1MpM/DR3g0CTbowvviKkXK9i3AmU+j/8gXuWuAxwhseMasIT",
	"in2JtNfg6OiLJMqGOShLmIiSSegIfTIPPQOUjjjzLqEkE9Ocp5dE7FTx75TlzIlTrShyl5URm8mAL045",
	"Zre3NBbAZ0ckUchkWSpZtiCyYA5AcCtVkcfNrqFaBlgTV8wv+QB48lZ4ucIsluN7PKBdPwjHYkQvJRni",
	"M6JqI6Z2fXrQeeQ/WS3MfOs/wmP8TGGpHXo3GB7glwkgGG3UCDBQ5lhi/mlEeZInEiLnKkXB/WGxV73k",
	"VK88V/jWHBWJNlxzKI/vHE4gfeIJkZU7GzIbTLKX2+ddZF86kpT4dpDEkvRjZ79IaYjP/C/ph4Jfxr7s",
	"GD/lz04MpvJuObjnr4RXE9vLWggX3OS8sDWxpBlJM6u8XF4q0RC/IvyCB7+ESCnLtzRaf0LvKP4b7hNN",
	"jf2XMT7NXI7sP4qvRmab1BQa3X+OX+Ix/pX0kl5a8MT/RqGSjvwnwR3IYdQ/49bciuTMZz5GaFMeqi/3",
	"qYqQ+AhHJvdsFDYafVRiujPos7XHfbhirtbO5V7k6Ks606fTP/mDJMrXJ2tezA0cMcVMVJxG55lgeWn0",
	"sJWFp9HLCRHDQ6CU3/JDSrOm4ZAWpcAlaF6Xu5NPUvP7C5vJ4FsDOZBJGPOSOfEISjInPi/QuAS5BJpM",
	"j3Mu/Exozj+p/eZhdgl2UEJQBuwSAbtiEE61gE75qTmhuhWF6eLd5SRCz2+fyoI85PSmFckcMgaXisEt",
	"yB1fo5Gm4MOqLQPVGgLiID9z1LEdviKgkCBwva5Jq5+H7T4+Db6qFt5rL9fBbznC/x6pRLiLcXH4ZgHk",
	"aeAdvCH9+NKI9g/8RxLREtEcoiOVmB/R0QdZveKNpbfjcsvxquPv0y75M3yJhmSuWmJuEfFrsv7GY7qS",
	"HvgHCcRxCEtDbm2ffkG4cHdbDLxb9RlX1uFnil8b2ykhKiG6mCBYGpdTxb0SyM0PfK00Qpe1VS3zYf0l",
	"HwiRlCApYVHRrdLGmvsqP0Uy/z3+O7sEYKxxhvOkfO+DDrCcVhPYKBBR1dS2awWf5q+s0fPcVsPxUOWK",
	"fkVf66yrvd3e/wMAAP//Ns5m7t6rAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
