// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateTimeSlotRequestType.
const (
	CreateTimeSlotRequestTypeRecurring CreateTimeSlotRequestType = "recurring"
	CreateTimeSlotRequestTypeSingle    CreateTimeSlotRequestType = "single"
)

// Defines values for GetAvailableServicesResponseStatus.
const (
	BLOCKED    GetAvailableServicesResponseStatus = "BLOCKED"
	TOOLONGAGO GetAvailableServicesResponseStatus = "TOO_LONG_AGO"
)

// Defines values for RecurrenceEndType.
const (
	Date  RecurrenceEndType = "date"
	Never RecurrenceEndType = "never"
)

// Defines values for RecurrenceFrequency.
const (
	Daily   RecurrenceFrequency = "daily"
	Monthly RecurrenceFrequency = "monthly"
	Weekly  RecurrenceFrequency = "weekly"
)

// Defines values for TimeSlotStatus.
const (
	TimeSlotStatusActive   TimeSlotStatus = "active"
	TimeSlotStatusArchived TimeSlotStatus = "archived"
)

// Defines values for TimeSlotType.
const (
	TimeSlotTypeRecurring TimeSlotType = "recurring"
	TimeSlotTypeSingle    TimeSlotType = "single"
)

// Defines values for GetEventsParamsStatus.
const (
	Past     GetEventsParamsStatus = "past"
	Upcoming GetEventsParamsStatus = "upcoming"
)

// Defines values for GetTimeSlotsParamsStatus.
const (
	GetTimeSlotsParamsStatusActive   GetTimeSlotsParamsStatus = "active"
	GetTimeSlotsParamsStatusArchived GetTimeSlotsParamsStatus = "archived"
)

// AddParticipantToEventRequest defines model for AddParticipantToEventRequest.
type AddParticipantToEventRequest struct {
	ParticipantId int64 `json:"participant_id"`
	VolunteerId   int64 `json:"volunteer_id"`
}

// BlockClientRequest defines model for BlockClientRequest.
type BlockClientRequest struct {
	BlockReason *string `json:"block_reason,omitempty"`
	IsBlocked   bool    `json:"is_blocked"`
}

// Client defines model for Client.
type Client struct {
	BirthDate     *time.Time `json:"birth_date,omitempty"`
	BlockedAt     *time.Time `json:"blocked_at,omitempty"`
	BlockedReason *string    `json:"blocked_reason,omitempty"`
	FirstName     string     `json:"first_name"`
	Gender        *int32     `json:"gender,omitempty"`
	Id            int64      `json:"id"`
	IsBlocked     *bool      `json:"is_blocked,omitempty"`
	IsHomeless    *bool      `json:"is_homeless,omitempty"`
	IsNew         bool       `json:"is_new"`
	LastName      string     `json:"last_name"`
	MiddleName    string     `json:"middle_name"`
	PhotoName     *string    `json:"photo_name,omitempty"`
}

// CreateClientRequest defines model for CreateClientRequest.
type CreateClientRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// CreateLocationRequest defines model for CreateLocationRequest.
type CreateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// CreateTimeSlotRequest defines model for CreateTimeSlotRequest.
type CreateTimeSlotRequest struct {
	Capacity   int32                     `json:"capacity"`
	EndDate    time.Time                 `json:"endDate"`
	LocationId int64                     `json:"locationId"`
	Recurrence *Recurrence               `json:"recurrence,omitempty"`
	Services   []TimeSlotService         `json:"services"`
	StartDate  time.Time                 `json:"startDate"`
	Title      string                    `json:"title"`
	Type       CreateTimeSlotRequestType `json:"type"`
}

// CreateTimeSlotRequestType defines model for CreateTimeSlotRequest.Type.
type CreateTimeSlotRequestType string

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Capacity          int32     `json:"capacity"`
	Datetime          time.Time `json:"datetime"`
	Id                int64     `json:"id"`
	ParticipantsCount int32     `json:"participantsCount"`
	ServiceName       string    `json:"serviceName"`
	ServiceTypeId     int64     `json:"serviceTypeId"`
	TimeSlotServiceId int64     `json:"timeSlotServiceId"`
}

// GetAvailableServicesResponse defines model for GetAvailableServicesResponse.
type GetAvailableServicesResponse struct {
	Page       int32                              `json:"page"`
	PerPage    int32                              `json:"per_page"`
	Services   []ServiceType                      `json:"services"`
	Status     GetAvailableServicesResponseStatus `json:"status"`
	Total      int32                              `json:"total"`
	TotalPages int32                              `json:"total_pages"`
}

// GetAvailableServicesResponseStatus defines model for GetAvailableServicesResponse.Status.
type GetAvailableServicesResponseStatus string

// GetClientsResponse defines model for GetClientsResponse.
type GetClientsResponse struct {
	Clients    []Client `json:"clients"`
	Page       int32    `json:"page"`
	PerPage    int32    `json:"per_page"`
	Total      int32    `json:"total"`
	TotalPages int32    `json:"total_pages"`
}

// GetEventsResponse defines model for GetEventsResponse.
type GetEventsResponse struct {
	Items      []Event `json:"items"`
	Page       int32   `json:"page"`
	PerPage    int32   `json:"per_page"`
	Total      int32   `json:"total"`
	TotalPages int32   `json:"total_pages"`
}

// GetParticipantsResponse defines model for GetParticipantsResponse.
type GetParticipantsResponse struct {
	Page         int32         `json:"page"`
	Participants []Participant `json:"participants"`
	PerPage      int32         `json:"per_page"`
	Total        int32         `json:"total"`
	TotalPages   int32         `json:"total_pages"`
}

// GetServicesResponse defines model for GetServicesResponse.
type GetServicesResponse struct {
	Items      []ServiceType `json:"items"`
	Page       int32         `json:"page"`
	PerPage    int32         `json:"per_page"`
	Total      int32         `json:"total"`
	TotalPages int32         `json:"total_pages"`
}

// Location defines model for Location.
type Location struct {
	Address *string `json:"address,omitempty"`
	Id      int64   `json:"id"`
	Name    string  `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// Participant defines model for Participant.
type Participant struct {
	BirthDate            *time.Time `json:"birth_date,omitempty"`
	FirstName            string     `json:"first_name"`
	Id                   int64      `json:"id"`
	LastName             string     `json:"last_name"`
	MiddleName           string     `json:"middle_name"`
	PhotoName            *string    `json:"photo_name,omitempty"`
	VolounteerFirstName  string     `json:"volounteer_first_name"`
	VolounteerLastName   string     `json:"volounteer_last_name"`
	VolounteerMiddleName string     `json:"volounteer_middle_name"`
	VolunteerTg          int64      `json:"volunteer_tg"`
	VolunteerTgLogin     string     `json:"volunteer_tg_login"`
}

// Recurrence defines model for Recurrence.
type Recurrence struct {
	EndType   RecurrenceEndType   `json:"endType"`
	EndValue  *time.Time          `json:"endValue"`
	Frequency RecurrenceFrequency `json:"frequency"`
	Interval  int32               `json:"interval"`
}

// RecurrenceEndType defines model for Recurrence.EndType.
type RecurrenceEndType string

// RecurrenceFrequency defines model for Recurrence.Frequency.
type RecurrenceFrequency string

// ServiceType defines model for ServiceType.
type ServiceType struct {
	Id                    int64  `json:"id"`
	MinPeriodDays         int32  `json:"min_period_days"`
	Name                  string `json:"name"`
	RegistrationAvailable bool   `json:"registration_available"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	Capacity   int32             `json:"capacity"`
	EndDate    time.Time         `json:"endDate"`
	Id         int64             `json:"id"`
	LocationId int64             `json:"locationId"`
	Recurrence *Recurrence       `json:"recurrence,omitempty"`
	Services   []TimeSlotService `json:"services"`
	StartDate  time.Time         `json:"startDate"`
	Status     TimeSlotStatus    `json:"status"`
	Title      string            `json:"title"`
	Type       TimeSlotType      `json:"type"`
}

// TimeSlotStatus defines model for TimeSlot.Status.
type TimeSlotStatus string

// TimeSlotType defines model for TimeSlot.Type.
type TimeSlotType string

// TimeSlotService defines model for TimeSlotService.
type TimeSlotService struct {
	BookingWindow int32     `json:"bookingWindow"`
	Capacity      int32     `json:"capacity"`
	Id            *int64    `json:"id,omitempty"`
	ServiceTypeId int64     `json:"serviceTypeId"`
	Time          time.Time `json:"time"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Capacity int32     `json:"capacity"`
	Datetime time.Time `json:"datetime"`
}

// UpdateLocationRequest defines model for UpdateLocationRequest.
type UpdateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// UpdateServiceRegistrationRequest defines model for UpdateServiceRegistrationRequest.
type UpdateServiceRegistrationRequest struct {
	MinPeriodDays         int32 `json:"min_period_days"`
	RegistrationAvailable bool  `json:"registration_available"`
}

// UpdateVolunteerRequest defines model for UpdateVolunteerRequest.
type UpdateVolunteerRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// Volunteer defines model for Volunteer.
type Volunteer struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
	TgId       int64  `json:"tg_id"`
	TgLogin    string `json:"tg_login"`
}

// GetClientsParams defines parameters for GetClients.
type GetClientsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int   `form:"per_page" json:"per_page"`
}

// GetClientsIdEventsParams defines parameters for GetClientsIdEvents.
type GetClientsIdEventsParams struct {
	HistoryLimit *int32 `form:"history_limit,omitempty" json:"history_limit,omitempty"`
	Page         *int32 `form:"page,omitempty" json:"page,omitempty"`
	PerPage      *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetClientsIdServicesParams defines parameters for GetClientsIdServices.
type GetClientsIdServicesParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetClientsIdServicesServiceIdEventsParams defines parameters for GetClientsIdServicesServiceIdEvents.
type GetClientsIdServicesServiceIdEventsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	Page          int32                  `form:"page" json:"page"`
	PerPage       int32                  `form:"per_page" json:"per_page"`
	ParticipantId *int64                 `form:"participant_id,omitempty" json:"participant_id,omitempty"`
	Status        *GetEventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	LocationId    *int64                 `form:"location_id,omitempty" json:"location_id,omitempty"`
	ServiceId     *int64                 `form:"service_id,omitempty" json:"service_id,omitempty"`
	FromDate      *time.Time             `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate        *time.Time             `form:"to_date,omitempty" json:"to_date,omitempty"`
}

// GetEventsParamsStatus defines parameters for GetEvents.
type GetEventsParamsStatus string

// GetEventsServicesIdParams defines parameters for GetEventsServicesId.
type GetEventsServicesIdParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsIdParticipantsParams defines parameters for GetEventsIdParticipants.
type GetEventsIdParticipantsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	Page                  int32 `form:"page" json:"page"`
	PerPage               int32 `form:"per_page" json:"per_page"`
	RegistrationAvailable *bool `form:"registration_available,omitempty" json:"registration_available,omitempty"`
}

// GetTimeSlotsParams defines parameters for GetTimeSlots.
type GetTimeSlotsParams struct {
	Status    *GetTimeSlotsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	StartDate *time.Time                `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time                `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetTimeSlotsParamsStatus defines parameters for GetTimeSlots.
type GetTimeSlotsParamsStatus string

// PostClientsJSONRequestBody defines body for PostClients for application/json ContentType.
type PostClientsJSONRequestBody = CreateClientRequest

// PutClientsIdJSONRequestBody defines body for PutClientsId for application/json ContentType.
type PutClientsIdJSONRequestBody = BlockClientRequest

// PutEventsIdJSONRequestBody defines body for PutEventsId for application/json ContentType.
type PutEventsIdJSONRequestBody = UpdateEventRequest

// PutEventsIdParticipantsJSONRequestBody defines body for PutEventsIdParticipants for application/json ContentType.
type PutEventsIdParticipantsJSONRequestBody = AddParticipantToEventRequest

// PostLocationsJSONRequestBody defines body for PostLocations for application/json ContentType.
type PostLocationsJSONRequestBody = CreateLocationRequest

// PutLocationsIdJSONRequestBody defines body for PutLocationsId for application/json ContentType.
type PutLocationsIdJSONRequestBody = UpdateLocationRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PutServicesIdJSONRequestBody defines body for PutServicesId for application/json ContentType.
type PutServicesIdJSONRequestBody = UpdateServiceRegistrationRequest

// PostTimeSlotsJSONRequestBody defines body for PostTimeSlots for application/json ContentType.
type PostTimeSlotsJSONRequestBody = CreateTimeSlotRequest

// PutTimeSlotsIdJSONRequestBody defines body for PutTimeSlotsId for application/json ContentType.
type PutTimeSlotsIdJSONRequestBody = TimeSlot

// PostVolunteersJSONRequestBody defines body for PostVolunteers for application/json ContentType.
type PostVolunteersJSONRequestBody = Volunteer

// PutVolunteersTgIdJSONRequestBody defines body for PutVolunteersTgId for application/json ContentType.
type PutVolunteersTgIdJSONRequestBody = UpdateVolunteerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка живых клиентов
	// (GET /clients)
	GetClients(ctx echo.Context, params GetClientsParams) error
	// Создание нового клиента
	// (POST /clients)
	PostClients(ctx echo.Context) error
	// Получение клиента по идентификатору
	// (GET /clients/{id})
	GetClientsId(ctx echo.Context, id int64) error
	// Блокировка/Разблокировка клиента
	// (PUT /clients/{id})
	PutClientsId(ctx echo.Context, id int64) error
	// USE get events?participant_id={id}
	// (GET /clients/{id}/events)
	GetClientsIdEvents(ctx echo.Context, id int64, params GetClientsIdEventsParams) error
	// Получение списка услуг доступных клиенту
	// (GET /clients/{id}/services)
	GetClientsIdServices(ctx echo.Context, id int64, params GetClientsIdServicesParams) error
	// Получение списка событий доступных клиенту по услуге
	// (GET /clients/{id}/services/{service_id}/events)
	GetClientsIdServicesServiceIdEvents(ctx echo.Context, id int64, serviceId int64, params GetClientsIdServicesServiceIdEventsParams) error
	// Получение списка событий
	// (GET /events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// Получение списка событий по типу услуги
	// (GET /events/services/{id})
	GetEventsServicesId(ctx echo.Context, id int64, params GetEventsServicesIdParams) error
	// Удаление события по идентификатору
	// (DELETE /events/{id})
	DeleteEventsId(ctx echo.Context, id int64) error
	// Получение события по идентификатору
	// (GET /events/{id})
	GetEventsId(ctx echo.Context, id int64) error
	// Обновление события по идентификатору
	// (PUT /events/{id})
	PutEventsId(ctx echo.Context, id int64) error
	// Получение списка участников события
	// (GET /events/{id}/participants)
	GetEventsIdParticipants(ctx echo.Context, id int64, params GetEventsIdParticipantsParams) error
	// Добавление участника к событию
	// (PUT /events/{id}/participants)
	PutEventsIdParticipants(ctx echo.Context, id int64) error
	// Удаление участника из события
	// (DELETE /events/{id}/participants/{participant_id})
	DeleteEventsIdParticipantsParticipantId(ctx echo.Context, id int64, participantId int64) error
	// Получение списка локаций
	// (GET /locations)
	GetLocations(ctx echo.Context) error
	// Создание новой локации
	// (POST /locations)
	PostLocations(ctx echo.Context) error
	// Удаление локации по идентификатору
	// (DELETE /locations/{id})
	DeleteLocationsId(ctx echo.Context, id int64) error
	// Обновление локации по идентификатору
	// (PUT /locations/{id})
	PutLocationsId(ctx echo.Context, id int64) error
	// Вход в систему
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Получение списка услуг
	// (GET /services)
	GetServices(ctx echo.Context, params GetServicesParams) error
	// Получение информации об услуге по идентификатору
	// (GET /services/{id})
	GetServicesId(ctx echo.Context, id int64) error
	// Обновление информации об услуге по идентификатору
	// (PUT /services/{id})
	PutServicesId(ctx echo.Context, id int64) error
	// Получение списка временных слотов
	// (GET /timeSlots)
	GetTimeSlots(ctx echo.Context, params GetTimeSlotsParams) error
	// Создание нового временного слота
	// (POST /timeSlots)
	PostTimeSlots(ctx echo.Context) error
	// Удаление временного слота
	// (DELETE /timeSlots/{id})
	DeleteTimeSlotsId(ctx echo.Context, id int64) error
	// Получение временного слота по идентификатору
	// (GET /timeSlots/{id})
	GetTimeSlotsId(ctx echo.Context, id int64) error
	// Обновление временного слота
	// (PUT /timeSlots/{id})
	PutTimeSlotsId(ctx echo.Context, id int64) error
	// Активация временного слота
	// (PATCH /timeSlots/{id}/activate)
	PatchTimeSlotsIdActivate(ctx echo.Context, id int64) error
	// Архивация временного слота
	// (PATCH /timeSlots/{id}/archive)
	PatchTimeSlotsIdArchive(ctx echo.Context, id int64) error
	// Создание нового волонтера
	// (POST /volunteers)
	PostVolunteers(ctx echo.Context) error
	// Получение волонтера по идентификатору
	// (GET /volunteers/{tg_id})
	GetVolunteersTgId(ctx echo.Context, tgId int64) error
	// Обновление волонтера
	// (PUT /volunteers/{tg_id})
	PutVolunteersTgId(ctx echo.Context, tgId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClients converts echo context to params.
func (w *ServerInterfaceWrapper) GetClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClients(ctx, params)
	return err
}

// PostClients converts echo context to params.
func (w *ServerInterfaceWrapper) PostClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostClients(ctx)
	return err
}

// GetClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsId(ctx, id)
	return err
}

// PutClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutClientsId(ctx, id)
	return err
}

// GetClientsIdEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdEvents(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdEventsParams
	// ------------- Optional query parameter "history_limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "history_limit", ctx.QueryParams(), &params.HistoryLimit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter history_limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdEvents(ctx, id, params)
	return err
}

// GetClientsIdServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdServices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdServices(ctx, id, params)
	return err
}

// GetClientsIdServicesServiceIdEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdServicesServiceIdEvents(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "service_id" -------------
	var serviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "service_id", ctx.Param("service_id"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdServicesServiceIdEventsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdServicesServiceIdEvents(ctx, id, serviceId, params)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "participant_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "participant_id", ctx.QueryParams(), &params.ParticipantId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter participant_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "location_id", ctx.QueryParams(), &params.LocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter location_id: %s", err))
	}

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", ctx.QueryParams(), &params.ServiceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_id: %s", err))
	}

	// ------------- Optional query parameter "from_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_date", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from_date: %s", err))
	}

	// ------------- Optional query parameter "to_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_date", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to_date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetEventsServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsServicesIdParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsServicesId(ctx, id, params)
	return err
}

// DeleteEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventsId(ctx, id)
	return err
}

// GetEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsId(ctx, id)
	return err
}

// PutEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsId(ctx, id)
	return err
}

// GetEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsIdParticipantsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsIdParticipants(ctx, id, params)
	return err
}

// PutEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsIdParticipants(ctx, id)
	return err
}

// DeleteEventsIdParticipantsParticipantId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventsIdParticipantsParticipantId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "participant_id" -------------
	var participantId int64

	err = runtime.BindStyledParameterWithOptions("simple", "participant_id", ctx.Param("participant_id"), &participantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter participant_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventsIdParticipantsParticipantId(ctx, id, participantId)
	return err
}

// GetLocations converts echo context to params.
func (w *ServerInterfaceWrapper) GetLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLocations(ctx)
	return err
}

// PostLocations converts echo context to params.
func (w *ServerInterfaceWrapper) PostLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLocations(ctx)
	return err
}

// DeleteLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLocationsId(ctx, id)
	return err
}

// PutLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutLocationsId(ctx, id)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// GetServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetServices(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "registration_available" -------------

	err = runtime.BindQueryParameter("form", true, false, "registration_available", ctx.QueryParams(), &params.RegistrationAvailable)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter registration_available: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServices(ctx, params)
	return err
}

// GetServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServicesId(ctx, id)
	return err
}

// PutServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) PutServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutServicesId(ctx, id)
	return err
}

// GetTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimeSlotsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlots(ctx, params)
	return err
}

// PostTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) PostTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTimeSlots(ctx)
	return err
}

// DeleteTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTimeSlotsId(ctx, id)
	return err
}

// GetTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlotsId(ctx, id)
	return err
}

// PutTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTimeSlotsId(ctx, id)
	return err
}

// PatchTimeSlotsIdActivate converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdActivate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdActivate(ctx, id)
	return err
}

// PatchTimeSlotsIdArchive converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdArchive(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdArchive(ctx, id)
	return err
}

// PostVolunteers converts echo context to params.
func (w *ServerInterfaceWrapper) PostVolunteers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVolunteers(ctx)
	return err
}

// GetVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) GetVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVolunteersTgId(ctx, tgId)
	return err
}

// PutVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) PutVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutVolunteersTgId(ctx, tgId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/clients", wrapper.GetClients)
	router.POST(baseURL+"/clients", wrapper.PostClients)
	router.GET(baseURL+"/clients/:id", wrapper.GetClientsId)
	router.PUT(baseURL+"/clients/:id", wrapper.PutClientsId)
	router.GET(baseURL+"/clients/:id/events", wrapper.GetClientsIdEvents)
	router.GET(baseURL+"/clients/:id/services", wrapper.GetClientsIdServices)
	router.GET(baseURL+"/clients/:id/services/:service_id/events", wrapper.GetClientsIdServicesServiceIdEvents)
	router.GET(baseURL+"/events", wrapper.GetEvents)
	router.GET(baseURL+"/events/services/:id", wrapper.GetEventsServicesId)
	router.DELETE(baseURL+"/events/:id", wrapper.DeleteEventsId)
	router.GET(baseURL+"/events/:id", wrapper.GetEventsId)
	router.PUT(baseURL+"/events/:id", wrapper.PutEventsId)
	router.GET(baseURL+"/events/:id/participants", wrapper.GetEventsIdParticipants)
	router.PUT(baseURL+"/events/:id/participants", wrapper.PutEventsIdParticipants)
	router.DELETE(baseURL+"/events/:id/participants/:participant_id", wrapper.DeleteEventsIdParticipantsParticipantId)
	router.GET(baseURL+"/locations", wrapper.GetLocations)
	router.POST(baseURL+"/locations", wrapper.PostLocations)
	router.DELETE(baseURL+"/locations/:id", wrapper.DeleteLocationsId)
	router.PUT(baseURL+"/locations/:id", wrapper.PutLocationsId)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.GET(baseURL+"/services", wrapper.GetServices)
	router.GET(baseURL+"/services/:id", wrapper.GetServicesId)
	router.PUT(baseURL+"/services/:id", wrapper.PutServicesId)
	router.GET(baseURL+"/timeSlots", wrapper.GetTimeSlots)
	router.POST(baseURL+"/timeSlots", wrapper.PostTimeSlots)
	router.DELETE(baseURL+"/timeSlots/:id", wrapper.DeleteTimeSlotsId)
	router.GET(baseURL+"/timeSlots/:id", wrapper.GetTimeSlotsId)
	router.PUT(baseURL+"/timeSlots/:id", wrapper.PutTimeSlotsId)
	router.PATCH(baseURL+"/timeSlots/:id/activate", wrapper.PatchTimeSlotsIdActivate)
	router.PATCH(baseURL+"/timeSlots/:id/archive", wrapper.PatchTimeSlotsIdArchive)
	router.POST(baseURL+"/volunteers", wrapper.PostVolunteers)
	router.GET(baseURL+"/volunteers/:tg_id", wrapper.GetVolunteersTgId)
	router.PUT(baseURL+"/volunteers/:tg_id", wrapper.PutVolunteersTgId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd727bRrZ/FYL3Av3CRLTs5KYCLi6cPzdwGiRB4qYXN2sIjDiW2FCkSg6VaA0Bjt1s",
	"u0hQ73b3w2IXbbfbF1DcqFGsWHmF4RstZoZ/htSQov4ZSjJfAkcczpw5c87vnDnnzHBPrtnNlm0BC7py",
	"ZU92aw3Q1Mifm7p+R3OgUTNamgW37WttYMG74CsPuBA/B0+0ZssE+M9W3K5q6HJlTZHbtulZEACH/FDu",
	"KnLLsVvAgQZwea/sybu209SgXJENC17ckBUZdlqA/hfUgSN3050WeKWryA74yjMcoMuVB+lBUx3uRO/b",
	"D78ENYhHvGzatUdXTCNz6g9xg6oDNNe25IoMcQtFNtwqeYCHhY4HxqaffG0vHNiFjmHV8cBsD9Hjh7Zt",
	"As0amxfTmDcJSn+K8F3DcWHV0pq4LfobOkY9dIpJp+tnuNWG3QQmcF06BUU2tfEX0Agdy4rcNHTdBLyH",
	"aOB/Iytyq2FDO3xO/nP+yxaZaIovhgMbVV2DILG++Idz0GiCeI1jVgVTr2pw+ndyVoBlEOdxHVg6cNJS",
	"uF7mCm5hCc9f9tSyZDSwwGP+M2YBORNKrCHnObuEY4/TAomVi2FgsneWkohiruA6QIMgT/2ypHh2WR0T",
	"yQlyMA9TU1wrxLBsPt20axo0bIvPKU3XHSI1sn+Ihucl9AOZcs8/UqSL/yUrcsgQ8rv/HL2R/Gf+Puqh",
	"t+M8iTrjTLnYXIN5hR1lz2rbaIJ7pp2x/jWtpdUM2JEra6qqyMDSrxLskMtq+cI5df1cWd1e+7SiqhVV",
	"/X/Mx4BHWxTlHFDzHAdYNdIZsPRtSgQBINLdfc304v420v3t4jkBq9aRK/JjAB6ZHSzRFgROWzPlylpX",
	"kV3gtI0a5tuDPayNjwyr/oVh6fZjubKuKswUNtSoNaYjoJFAWHJCl0ICusqELi+Od1nO6HI96HJHkV2o",
	"OZDDyEvxxKEBTSIu/0J9/6l/IKF3RG4O0MjfR310igaoH0McZXSIJAlZioktBKXREheCekV+cq6tmQa1",
	"KA+wu2PpBpYAuRJ2Jf3OU9V1IMWzVmTHI7MLWzQ9F0oPgaTtQuAwDbs73aRMFQL5pNT9pwN25Yr8H6XY",
	"EysFbljpbtwyIUl7sgFB0530eqg79+iLuI+AGs1xtA7pM17q+RkadRay1LIfx8yMn4bsNCwJNoC060HP",
	"AUSYc3qrSeHS5/T4EOzaDohakvUJRJUDVfQHrPheE4OSa1h1k/QfieuOMgHIaO9Bq4QwMHrI8jkWYWZF",
	"efh3zXFsJ4V3OoCaYWIURz+hERqivvQJhtJPJDRCL/0j9Br1/APUR0P/BTZqEnqFhv6RhH8nGjpEp1Q7",
	"/SNsZIDranWixz/636IBeolOUE8iJnGIBugV6vl/QAM0GFfbiBKe1Qu7nWQFwobc6bfHndYYK8qqQqQ0",
	"hrKNAKVUBp4DZ5bx+90rtoe7XVMpDDLqQfB2XniKaSrqihb2DTmzKERSIGS3snyUlH0oRAuHddNvx8Y7",
	"SahMxMo0iQr1L9l58bjDE6rrAG62NcPUHpogGNa9C9yWbblgbFOLJRhLD3CqwX/UlDkP5CvyJf2n1Ayi",
	"PnrlvwhtKfSwwl6+efvKZ9euYrbYkDgH2GMhf5PuXfwLZ59cBwXXOaZzGrEobk3uxYuQYUnIRGM4jWe8",
	"fft29ebtW9erm9dvcyA1YkkhwhMsK/BGSuqieUckh8MrlNsMJ5ODZQgU3Z9kiVGNPiXiMmHPPcemZUfJ",
	"ktdphC2itaBEBIEFjjAsT2zPUFJCdswpH8SQZYlHwOcHM9s2vhGbrbsyt7vygqQrEqlCskXN/4cqWpQF",
	"cwoWE55NiNfsFoTpsPBCMVRwl2tl1yAx2zmXgudLzCP9E2yt0AHC+DDiNSnU9ZO/jwboLer7++iUhrzW",
	"yusxhoZm9S9oiHroGJ3OEf4q7M5PEUnNDPzdtOtGRrzPxI+wzOhNwyLcdd3HtqPLlfjPsYkFL/Giv9Hr",
	"kyimfTBv5BDONYnQfgRIeKZzo/Hwes24bdzY+vz3W2u3jC13y7p7oXZl6+LWo9b/3b9y49PxKQRvT6KS",
	"NuORxuJZKtfDJCeyzOjSXLzMHArJYtlBGitreKZJDglMq4nUxKkzWE9l/GC9Gkqf0dasKv7Hbi8m2TMh",
	"Gl9Y+5aYC8lckPyW+RRlLQ2/KbMyUyZW47VbZI4nQRJ3uCymZc48g3c8jb6bjPLHCj0h4L8xW8A/KeTR",
	"GPG+2AJt4AQBDu5uOCYjQy0szyQhjDA1O64mMZnxuLpmEHIjupu2BRtmh0tDPCeOZW8altHEna5NtPIx",
	"JUyfSsQW3nqxzk9qt0RRtGlY1RZwDFuv6lrHzY3BYGrqhgsd4ilUtTD6k5GYLwwgYzQUcpkylTaLyMm5",
	"/8hBGKcps1se18NkQWbI9UI6wRbavzV1bFeayrMVz4GVJ+TAeDY33LNGe9/cEdYnpMSYEdb5I4xnyHhU",
	"RYE/rQaNNmBzZr/4B0GS7NQ/8o8k/yka+ofoN/QS9RijR7MRZ5swm8qGfkyJL26EM1pazak1jHai/oYJ",
	"bi41AUUAYL4sVBgGzU1HpXma8o0Xq9TjvmKy/0KSP6WiFJb7WRMmRSWNH7COkh/Meia5EozCW7zPW3i8",
	"nBK+6cKFZ50lSwdmOUmi7Fl/aHUxdFaBGt5lDDx/gjxnaSqXaDZPZ2aHZi4nhvLmfri/mK5o7AOsDIs4",
	"sfS6OUWG9bD4lwkAQODCarTfO1MeRhQVA+jCG1/aK/OGMuv6EFtS8xwDdu5hz4Wy5DLQHOBserBBDB/5",
	"3/+GE7jxxTY21KQ1ViLyNJ5QA8KW3O2S/duuTes03JpjtIKams07W2FJiH+I3hEcO0bDsCREQsfEMX0b",
	"OKfP0Vs0IO4pGvkHGPPQQJHw/9AJLQ3xj0gT3OowcGN/pe0kdCyhHnqF/ya9PyVeb88/QAN0TCTnjYTe",
	"ESHqoyEaSPc0w4LStbqhGzbjLrM/S5t607CkzTtbsiK3gePSaa2dV8+reBXtFrC0liFX5HXykyK3NNgg",
	"bC0x2c06IJiABTHyYJlULi0n0JoAAidI9ONRvvKA04ktQhCkjkWD7sWpD0pZv6t5JiQqMeUWOmPEODSe",
	"PepYZzu4NY20ksmXVZWYbNuCQYWN1mqZBjWSpS+Deui4w0IeNycPPuZ0Y7FMiiP6hezW+/63QcydiNkx",
	"6vsH+PWNKSnNzSeSaioeDZMrnzbUteXTsVmrAdeVdGAZgITmL5zF7LcsCBxLMyXsZQJHAkFDRXa9ZlNz",
	"OlGpmX/ofxMWdkpk2Qb+U8q037BG+8/9ZxI6Idzro1P/ILAbUKu7bDZ9B9sA2+Uo4B3bZTTQobb7sq13",
	"FsYGXkF5t0sBPqEhi1vvsEZCCP97Kvw/oxF6jVkSiH7g84zQr2iUlPceV9q7SmR6SnuG3i1gf8g2L2WB",
	"wJOWaetAruxqpgsUah+wcYvNA/FKsg1DkZ0t7NDCWoM4inObDqEYC1eMDXXjDGb/91isscATqe+hN+gV",
	"/m3VjVNSKcnJBIksHv1l4H+NBsR/JYcV/MMsI+XxbJS3mkq6eFvJOfrINZUCEQQirBYi/DnYoA78fWKq",
	"T1CvhP6Jeug1ejn+aBYbXgLt1FZSBy0H1DQY63S2cacFoSuCHhlbzYbhQtvpVE2jaUCZu6tdV4qUfOXu",
	"nQvulWfYH3N6vlCk52V6POO1wALqBNTNA3Wf37sm1QGUKBz9T/J+g/8mu41CcMYmWCfuTe7FByhWGMBW",
	"NDoXjVpWecNqT4JhVXUCEUsGquxTUgKzBGYtM5oY5xEk9AqNSNrgEL3DkpUKMGbs3DLRrbQX/FXlunCT",
	"ES86FLNqHlyBceOprwoAL8LNm6d34eoJ2PyAYPMpuQHgOUmvvpkMnTQsxiRt+5lgOhkps/DwY3TMMuEw",
	"dffYFJib1WdcuBf1FVYSeq2a3aQXdrQ0F3LLCPmdhrWDi6OStTwL6G/XsZvVoGCf011uGRm/R2jP2J8w",
	"ISKHuHDsZnA4QF4WhhlvNplMLBCBpPIUerMrk8AQO3gBHh+n/3nLhtKu7Vn6e+1qEkcS//3OP2Q9ysEE",
	"JAsBTAcmoOcwkoh1lfxO5fiDKYlIlr+6HpG7jLLodLmo0GChwcU0+BdSsDRk9TdSWf9oqpKISHOVCdu/",
	"j6JqKbiWRqiiUMV5jOkClDGrPGkVlXHx1UmcA23d5EGN4CyTQAKBBCuCBD+il0Hx8GINc8qlLqWv8Zpk",
	"tu8kL8ISIYEPNSTAvTBOINgqJqZ+ZrbY/fHUFBpNn1X/BvX8p/4BeXqCYSgFPrO5GSsIHktyOXI/iMMt",
	"jd5YTGQgOrebuOxHBAreX59kQ/30bEYElu3VG1J0YQIeu1xe/ti0dEbSTAdoekdqJe8IXR2X7K8YANkz",
	"0Bg301DZk9BJEiu/m9YNK+0l879TxD1ZgGX+XqXsTYFxx9LfS474COgVKdr5IqYcFBig1wV8JowDYRFF",
	"7v7rZtToLE7oR5fldsmWZIu+Q2/uFsf0P4Zj+sy1HYkqg1hY88/mJ+V1Wafz09c1FQrrFVn4aS59MnRy",
	"vin/7qdis4r1jiPU/2BvUqG500DP0IhCTXj0vCc07T24E+BNUssGGVqWMBEF8+CR9olU+AyqdMiYd6FK",
	"IjfOeHpJjZ0qBJ+ynBmhshXV3GUl5WYy4IsTjtntLYkFsAkaARQiX5fK1y0ILKgDEFw3mOdx0/sFl6Gs",
	"iW+HLPlmj+TnPsQOM5+OH1CfTH0/5MWQ3DY1QKdY1IZU7HrkBouh/2K1dOZ7/xkaoVcSzS6RSx9RH71N",
	"KILmwUagA0UOnmefNxfHiyIiMu7I5VwMGXvVS842i5PjH835lajmm9Hy+DL5hKZPvANv5Y6nzKYm418t",
	"yfxKbNFIUuKjcEKXhB87+w15A3Tqf00+1f829mVH6GXiQPBU3i2j7tk74dXU7WVthHOu6F/YnljAjICZ",
	"Vd4uLxVosF8RfpopeRlfQli+J9H6Y3L5/B9RD0tq7L+M0MnYrff+s/jOe1onJ5Ho/mv0Fo3Qb3iW5G6F",
	"F/53EqF06L8ILrcPo/5jbs12RGc28lFAm/Kkf7FvEIXAhzEyWbORO2j0taDpDsbPNh7zRaK5RjuTC++j",
	"z6VNn06//ZkAyvcna56PDQwwxUiUn0ZnkWB5afRwlIWn0YsREasHRyi/Z1lKsqYhS/NS4EJp3pdL8Y9T",
	"6/srXcngIzIZKpMw5gVz4pEqiZz4vIrGJMiFoon0OOPCz6TN2YfFPzydXYIdFCooAnaJgF2+Ek61gU75",
	"qRmhuhVV08W7y0kNPbs6lQV5yOmiFYEcIgaXisEtyB0vkUhT8MXslgZrDQ5w4J8Z6NgMX+FASBC4XlOE",
	"1c/S7R46CT6XGX6wROyDP3IN/1MkEmEV4+L0mwaQp1Hv4A3hxxfWaH/ffyY0Wmg0o9GRSMyv0dGXtt38",
	"wtL7cbvleNXxh8eX/H3VxEAiVy10bhHxa7z/RiOyk+77+wmNYzQsrXKlPfJp+Nzqtljxtusz7qzD78+/",
	"N7ZTqKhQ0cUEwdJ6OVXcK6G52YGvldbQZZWqRZM+owMhAhIEJCwqulXYWOPOQM1zDNghmnwZaA5wNj3Y",
	"kCsPdrCC0cGpnifpuwrawLRbTWDBgERZkT3HlCtyA8JWpUTOc5sN24WVS+oltdRek7s73X8HAAD//xlW",
	"itlgswAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
