// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateTimeSlotRequestType.
const (
	CreateTimeSlotRequestTypeRecurring CreateTimeSlotRequestType = "recurring"
	CreateTimeSlotRequestTypeSingle    CreateTimeSlotRequestType = "single"
)

// Defines values for RecurrenceEndType.
const (
	Date  RecurrenceEndType = "date"
	Never RecurrenceEndType = "never"
)

// Defines values for RecurrenceFrequency.
const (
	Daily   RecurrenceFrequency = "daily"
	Monthly RecurrenceFrequency = "monthly"
	Weekly  RecurrenceFrequency = "weekly"
)

// Defines values for TimeSlotStatus.
const (
	TimeSlotStatusActive   TimeSlotStatus = "active"
	TimeSlotStatusArchived TimeSlotStatus = "archived"
)

// Defines values for TimeSlotType.
const (
	TimeSlotTypeRecurring TimeSlotType = "recurring"
	TimeSlotTypeSingle    TimeSlotType = "single"
)

// Defines values for GetEventsParamsStatus.
const (
	Past     GetEventsParamsStatus = "past"
	Upcoming GetEventsParamsStatus = "upcoming"
)

// Defines values for GetTimeSlotsParamsStatus.
const (
	GetTimeSlotsParamsStatusActive   GetTimeSlotsParamsStatus = "active"
	GetTimeSlotsParamsStatusArchived GetTimeSlotsParamsStatus = "archived"
)

// AddParticipantToEventRequest defines model for AddParticipantToEventRequest.
type AddParticipantToEventRequest struct {
	ParticipantId int64 `json:"participant_id"`
}

// BlockClientRequest defines model for BlockClientRequest.
type BlockClientRequest struct {
	IsBlocked bool `json:"is_blocked"`
}

// Client defines model for Client.
type Client struct {
	BirthDate  *time.Time `json:"birth_date,omitempty"`
	FirstName  string     `json:"first_name"`
	Gender     *int32     `json:"gender,omitempty"`
	Id         int64      `json:"id"`
	IsBlocked  *bool      `json:"is_blocked,omitempty"`
	IsHomeless *bool      `json:"is_homeless,omitempty"`
	IsNew      bool       `json:"is_new"`
	LastName   string     `json:"last_name"`
	MiddleName string     `json:"middle_name"`
	PhotoName  *string    `json:"photo_name,omitempty"`
}

// CreateClientRequest defines model for CreateClientRequest.
type CreateClientRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// CreateLocationRequest defines model for CreateLocationRequest.
type CreateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// CreateTimeSlotRequest defines model for CreateTimeSlotRequest.
type CreateTimeSlotRequest struct {
	Capacity   int32                     `json:"capacity"`
	EndDate    time.Time                 `json:"endDate"`
	LocationId int64                     `json:"locationId"`
	Recurrence *Recurrence               `json:"recurrence,omitempty"`
	Services   []TimeSlotService         `json:"services"`
	StartDate  time.Time                 `json:"startDate"`
	Title      string                    `json:"title"`
	Type       CreateTimeSlotRequestType `json:"type"`
}

// CreateTimeSlotRequestType defines model for CreateTimeSlotRequest.Type.
type CreateTimeSlotRequestType string

// Error defines model for Error.
type Error struct {
	Code    string  `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Capacity          int32     `json:"capacity"`
	Datetime          time.Time `json:"datetime"`
	Id                int64     `json:"id"`
	ServiceTypeId     int64     `json:"serviceTypeId"`
	TimeSlotServiceId int64     `json:"timeSlotServiceId"`
}

// GetAvailableServicesResponse defines model for GetAvailableServicesResponse.
type GetAvailableServicesResponse struct {
	Services []ServiceType `json:"services"`
}

// GetClientsResponse defines model for GetClientsResponse.
type GetClientsResponse struct {
	Clients    []Client `json:"clients"`
	Page       int32    `json:"page"`
	PerPage    int32    `json:"per_page"`
	Total      int32    `json:"total"`
	TotalPages int32    `json:"total_pages"`
}

// GetEventsResponse defines model for GetEventsResponse.
type GetEventsResponse struct {
	Items      []Event `json:"items"`
	Page       int32   `json:"page"`
	PerPage    int32   `json:"per_page"`
	Total      int32   `json:"total"`
	TotalPages int32   `json:"total_pages"`
}

// GetParticipantsResponse defines model for GetParticipantsResponse.
type GetParticipantsResponse struct {
	Page         int32         `json:"page"`
	Participants []Participant `json:"participants"`
	PerPage      int32         `json:"per_page"`
	Total        int32         `json:"total"`
	TotalPages   int32         `json:"total_pages"`
}

// GetServicesResponse defines model for GetServicesResponse.
type GetServicesResponse struct {
	Items      []ServiceType `json:"items"`
	Page       int32         `json:"page"`
	PerPage    int32         `json:"per_page"`
	Total      int32         `json:"total"`
	TotalPages int32         `json:"total_pages"`
}

// Location defines model for Location.
type Location struct {
	Address *string `json:"address,omitempty"`
	Id      int64   `json:"id"`
	Name    string  `json:"name"`
}

// Participant defines model for Participant.
type Participant struct {
	BirthDate     *time.Time `json:"birth_date,omitempty"`
	FirstName     string     `json:"first_name"`
	Id            int64      `json:"id"`
	LastName      string     `json:"last_name"`
	MiddleName    string     `json:"middle_name"`
	VolunteerName string     `json:"volunteer_name"`
	VolunteerTg   int64      `json:"volunteer_tg"`
}

// Recurrence defines model for Recurrence.
type Recurrence struct {
	EndType   RecurrenceEndType   `json:"endType"`
	EndValue  *time.Time          `json:"endValue"`
	Frequency RecurrenceFrequency `json:"frequency"`
	Interval  int32               `json:"interval"`
}

// RecurrenceEndType defines model for Recurrence.EndType.
type RecurrenceEndType string

// RecurrenceFrequency defines model for Recurrence.Frequency.
type RecurrenceFrequency string

// ServiceType defines model for ServiceType.
type ServiceType struct {
	Id                    int64  `json:"id"`
	MinPeriodDays         int32  `json:"min_period_days"`
	Name                  string `json:"name"`
	RegistrationAvailable bool   `json:"registration_available"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	Capacity   int32             `json:"capacity"`
	EndDate    time.Time         `json:"endDate"`
	Id         int64             `json:"id"`
	LocationId int64             `json:"locationId"`
	Recurrence *Recurrence       `json:"recurrence,omitempty"`
	Services   []TimeSlotService `json:"services"`
	StartDate  time.Time         `json:"startDate"`
	Status     TimeSlotStatus    `json:"status"`
	Title      string            `json:"title"`
	Type       TimeSlotType      `json:"type"`
}

// TimeSlotStatus defines model for TimeSlot.Status.
type TimeSlotStatus string

// TimeSlotType defines model for TimeSlot.Type.
type TimeSlotType string

// TimeSlotService defines model for TimeSlotService.
type TimeSlotService struct {
	BookingWindow int32     `json:"bookingWindow"`
	Capacity      int32     `json:"capacity"`
	Id            *int64    `json:"id,omitempty"`
	ServiceTypeId int64     `json:"serviceTypeId"`
	Time          time.Time `json:"time"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Capacity int32     `json:"capacity"`
	Datetime time.Time `json:"datetime"`
}

// UpdateLocationRequest defines model for UpdateLocationRequest.
type UpdateLocationRequest struct {
	Address string `json:"address"`
	Name    string `json:"name"`
}

// UpdateServiceRegistrationRequest defines model for UpdateServiceRegistrationRequest.
type UpdateServiceRegistrationRequest struct {
	MinPeriodDays         int32 `json:"min_period_days"`
	RegistrationAvailable bool  `json:"registration_available"`
}

// UpdateVolunteerRequest defines model for UpdateVolunteerRequest.
type UpdateVolunteerRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
}

// Volunteer defines model for Volunteer.
type Volunteer struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
	TgId       int64  `json:"tg_id"`
	TgLogin    string `json:"tg_login"`
}

// GetClientsParams defines parameters for GetClients.
type GetClientsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int   `form:"per_page" json:"per_page"`
}

// GetClientsIdServicesParams defines parameters for GetClientsIdServices.
type GetClientsIdServicesParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	Page          int32                  `form:"page" json:"page"`
	PerPage       int32                  `form:"per_page" json:"per_page"`
	ParticipantId *int64                 `form:"participant_id,omitempty" json:"participant_id,omitempty"`
	Status        *GetEventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	LocationId    *int64                 `form:"location_id,omitempty" json:"location_id,omitempty"`
	ServiceId     *int64                 `form:"service_id,omitempty" json:"service_id,omitempty"`
	FromDate      *time.Time             `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate        *time.Time             `form:"to_date,omitempty" json:"to_date,omitempty"`
}

// GetEventsParamsStatus defines parameters for GetEvents.
type GetEventsParamsStatus string

// GetEventsServicesIdParams defines parameters for GetEventsServicesId.
type GetEventsServicesIdParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetEventsIdParticipantsParams defines parameters for GetEventsIdParticipants.
type GetEventsIdParticipantsParams struct {
	Page    int32 `form:"page" json:"page"`
	PerPage int32 `form:"per_page" json:"per_page"`
}

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	Page                  int32 `form:"page" json:"page"`
	PerPage               int32 `form:"per_page" json:"per_page"`
	RegistrationAvailable *bool `form:"registration_available,omitempty" json:"registration_available,omitempty"`
}

// GetTimeSlotsParams defines parameters for GetTimeSlots.
type GetTimeSlotsParams struct {
	Status    *GetTimeSlotsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	StartDate *time.Time                `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time                `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetTimeSlotsParamsStatus defines parameters for GetTimeSlots.
type GetTimeSlotsParamsStatus string

// PostClientsJSONRequestBody defines body for PostClients for application/json ContentType.
type PostClientsJSONRequestBody = CreateClientRequest

// PutClientsIdJSONRequestBody defines body for PutClientsId for application/json ContentType.
type PutClientsIdJSONRequestBody = BlockClientRequest

// PutEventsIdJSONRequestBody defines body for PutEventsId for application/json ContentType.
type PutEventsIdJSONRequestBody = UpdateEventRequest

// PutEventsIdParticipantsJSONRequestBody defines body for PutEventsIdParticipants for application/json ContentType.
type PutEventsIdParticipantsJSONRequestBody = AddParticipantToEventRequest

// PostLocationsJSONRequestBody defines body for PostLocations for application/json ContentType.
type PostLocationsJSONRequestBody = CreateLocationRequest

// PutLocationsIdJSONRequestBody defines body for PutLocationsId for application/json ContentType.
type PutLocationsIdJSONRequestBody = UpdateLocationRequest

// PutServicesIdJSONRequestBody defines body for PutServicesId for application/json ContentType.
type PutServicesIdJSONRequestBody = UpdateServiceRegistrationRequest

// PostTimeSlotsJSONRequestBody defines body for PostTimeSlots for application/json ContentType.
type PostTimeSlotsJSONRequestBody = CreateTimeSlotRequest

// PutTimeSlotsIdJSONRequestBody defines body for PutTimeSlotsId for application/json ContentType.
type PutTimeSlotsIdJSONRequestBody = TimeSlot

// PostVolunteersJSONRequestBody defines body for PostVolunteers for application/json ContentType.
type PostVolunteersJSONRequestBody = Volunteer

// PutVolunteersTgIdJSONRequestBody defines body for PutVolunteersTgId for application/json ContentType.
type PutVolunteersTgIdJSONRequestBody = UpdateVolunteerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка живых клиентов
	// (GET /clients)
	GetClients(ctx echo.Context, params GetClientsParams) error
	// Создание нового клиента
	// (POST /clients)
	PostClients(ctx echo.Context) error
	// Получение клиента по идентификатору
	// (GET /clients/{id})
	GetClientsId(ctx echo.Context, id int64) error
	// Блокировка/Разблокировка клиента
	// (PUT /clients/{id})
	PutClientsId(ctx echo.Context, id int64) error
	// Получение списка услуг доступных клиенту
	// (GET /clients/{id}/services)
	GetClientsIdServices(ctx echo.Context, id int64, params GetClientsIdServicesParams) error
	// Получение списка событий
	// (GET /events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// Получение списка событий по типу услуги
	// (GET /events/services/{id})
	GetEventsServicesId(ctx echo.Context, id int64, params GetEventsServicesIdParams) error
	// Удаление события по идентификатору
	// (DELETE /events/{id})
	DeleteEventsId(ctx echo.Context, id int64) error
	// Получение события по идентификатору
	// (GET /events/{id})
	GetEventsId(ctx echo.Context, id int64) error
	// Обновление события по идентификатору
	// (PUT /events/{id})
	PutEventsId(ctx echo.Context, id int64) error
	// Получение списка участников события
	// (GET /events/{id}/participants)
	GetEventsIdParticipants(ctx echo.Context, id int64, params GetEventsIdParticipantsParams) error
	// Добавление участника к событию
	// (PUT /events/{id}/participants)
	PutEventsIdParticipants(ctx echo.Context, id int64) error
	// Получение списка локаций
	// (GET /locations)
	GetLocations(ctx echo.Context) error
	// Создание новой локации
	// (POST /locations)
	PostLocations(ctx echo.Context) error
	// Удаление локации по идентификатору
	// (DELETE /locations/{id})
	DeleteLocationsId(ctx echo.Context, id int64) error
	// Обновление локации по идентификатору
	// (PUT /locations/{id})
	PutLocationsId(ctx echo.Context, id int64) error
	// Получение списка услуг
	// (GET /services)
	GetServices(ctx echo.Context, params GetServicesParams) error
	// Получение информации об услуге по идентификатору
	// (GET /services/{id})
	GetServicesId(ctx echo.Context, id int64) error
	// Обновление информации об услуге по идентификатору
	// (PUT /services/{id})
	PutServicesId(ctx echo.Context, id int64) error
	// Получение списка временных слотов
	// (GET /timeSlots)
	GetTimeSlots(ctx echo.Context, params GetTimeSlotsParams) error
	// Создание нового временного слота
	// (POST /timeSlots)
	PostTimeSlots(ctx echo.Context) error
	// Удаление временного слота
	// (DELETE /timeSlots/{id})
	DeleteTimeSlotsId(ctx echo.Context, id int64) error
	// Получение временного слота по идентификатору
	// (GET /timeSlots/{id})
	GetTimeSlotsId(ctx echo.Context, id int64) error
	// Обновление временного слота
	// (PUT /timeSlots/{id})
	PutTimeSlotsId(ctx echo.Context, id int64) error
	// Активация временного слота
	// (PATCH /timeSlots/{id}/activate)
	PatchTimeSlotsIdActivate(ctx echo.Context, id int64) error
	// Архивация временного слота
	// (PATCH /timeSlots/{id}/archive)
	PatchTimeSlotsIdArchive(ctx echo.Context, id int64) error
	// Создание нового волонтера
	// (POST /volunteers)
	PostVolunteers(ctx echo.Context) error
	// Получение волонтера по идентификатору
	// (GET /volunteers/{tg_id})
	GetVolunteersTgId(ctx echo.Context, tgId int64) error
	// Обновление волонтера
	// (PUT /volunteers/{tg_id})
	PutVolunteersTgId(ctx echo.Context, tgId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClients converts echo context to params.
func (w *ServerInterfaceWrapper) GetClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClients(ctx, params)
	return err
}

// PostClients converts echo context to params.
func (w *ServerInterfaceWrapper) PostClients(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostClients(ctx)
	return err
}

// GetClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsId(ctx, id)
	return err
}

// PutClientsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutClientsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutClientsId(ctx, id)
	return err
}

// GetClientsIdServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetClientsIdServices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClientsIdServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClientsIdServices(ctx, id, params)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "participant_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "participant_id", ctx.QueryParams(), &params.ParticipantId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter participant_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "location_id", ctx.QueryParams(), &params.LocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter location_id: %s", err))
	}

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", ctx.QueryParams(), &params.ServiceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_id: %s", err))
	}

	// ------------- Optional query parameter "from_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_date", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from_date: %s", err))
	}

	// ------------- Optional query parameter "to_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_date", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to_date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetEventsServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsServicesIdParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsServicesId(ctx, id, params)
	return err
}

// DeleteEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventsId(ctx, id)
	return err
}

// GetEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsId(ctx, id)
	return err
}

// PutEventsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsId(ctx, id)
	return err
}

// GetEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsIdParticipantsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsIdParticipants(ctx, id, params)
	return err
}

// PutEventsIdParticipants converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventsIdParticipants(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutEventsIdParticipants(ctx, id)
	return err
}

// GetLocations converts echo context to params.
func (w *ServerInterfaceWrapper) GetLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLocations(ctx)
	return err
}

// PostLocations converts echo context to params.
func (w *ServerInterfaceWrapper) PostLocations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLocations(ctx)
	return err
}

// DeleteLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLocationsId(ctx, id)
	return err
}

// PutLocationsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutLocationsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutLocationsId(ctx, id)
	return err
}

// GetServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetServices(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, true, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "registration_available" -------------

	err = runtime.BindQueryParameter("form", true, false, "registration_available", ctx.QueryParams(), &params.RegistrationAvailable)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter registration_available: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServices(ctx, params)
	return err
}

// GetServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServicesId(ctx, id)
	return err
}

// PutServicesId converts echo context to params.
func (w *ServerInterfaceWrapper) PutServicesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutServicesId(ctx, id)
	return err
}

// GetTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimeSlotsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlots(ctx, params)
	return err
}

// PostTimeSlots converts echo context to params.
func (w *ServerInterfaceWrapper) PostTimeSlots(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTimeSlots(ctx)
	return err
}

// DeleteTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTimeSlotsId(ctx, id)
	return err
}

// GetTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTimeSlotsId(ctx, id)
	return err
}

// PutTimeSlotsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutTimeSlotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTimeSlotsId(ctx, id)
	return err
}

// PatchTimeSlotsIdActivate converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdActivate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdActivate(ctx, id)
	return err
}

// PatchTimeSlotsIdArchive converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTimeSlotsIdArchive(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTimeSlotsIdArchive(ctx, id)
	return err
}

// PostVolunteers converts echo context to params.
func (w *ServerInterfaceWrapper) PostVolunteers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVolunteers(ctx)
	return err
}

// GetVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) GetVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVolunteersTgId(ctx, tgId)
	return err
}

// PutVolunteersTgId converts echo context to params.
func (w *ServerInterfaceWrapper) PutVolunteersTgId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tg_id" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tg_id", ctx.Param("tg_id"), &tgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tg_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutVolunteersTgId(ctx, tgId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/clients", wrapper.GetClients)
	router.POST(baseURL+"/clients", wrapper.PostClients)
	router.GET(baseURL+"/clients/:id", wrapper.GetClientsId)
	router.PUT(baseURL+"/clients/:id", wrapper.PutClientsId)
	router.GET(baseURL+"/clients/:id/services", wrapper.GetClientsIdServices)
	router.GET(baseURL+"/events", wrapper.GetEvents)
	router.GET(baseURL+"/events/services/:id", wrapper.GetEventsServicesId)
	router.DELETE(baseURL+"/events/:id", wrapper.DeleteEventsId)
	router.GET(baseURL+"/events/:id", wrapper.GetEventsId)
	router.PUT(baseURL+"/events/:id", wrapper.PutEventsId)
	router.GET(baseURL+"/events/:id/participants", wrapper.GetEventsIdParticipants)
	router.PUT(baseURL+"/events/:id/participants", wrapper.PutEventsIdParticipants)
	router.GET(baseURL+"/locations", wrapper.GetLocations)
	router.POST(baseURL+"/locations", wrapper.PostLocations)
	router.DELETE(baseURL+"/locations/:id", wrapper.DeleteLocationsId)
	router.PUT(baseURL+"/locations/:id", wrapper.PutLocationsId)
	router.GET(baseURL+"/services", wrapper.GetServices)
	router.GET(baseURL+"/services/:id", wrapper.GetServicesId)
	router.PUT(baseURL+"/services/:id", wrapper.PutServicesId)
	router.GET(baseURL+"/timeSlots", wrapper.GetTimeSlots)
	router.POST(baseURL+"/timeSlots", wrapper.PostTimeSlots)
	router.DELETE(baseURL+"/timeSlots/:id", wrapper.DeleteTimeSlotsId)
	router.GET(baseURL+"/timeSlots/:id", wrapper.GetTimeSlotsId)
	router.PUT(baseURL+"/timeSlots/:id", wrapper.PutTimeSlotsId)
	router.PATCH(baseURL+"/timeSlots/:id/activate", wrapper.PatchTimeSlotsIdActivate)
	router.PATCH(baseURL+"/timeSlots/:id/archive", wrapper.PatchTimeSlotsIdArchive)
	router.POST(baseURL+"/volunteers", wrapper.PostVolunteers)
	router.GET(baseURL+"/volunteers/:tg_id", wrapper.GetVolunteersTgId)
	router.PUT(baseURL+"/volunteers/:tg_id", wrapper.PutVolunteersTgId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdbW/cxvH/KsT+/0De0D7qIal775TaCdQGjSGrDlBXOFDH1YkJj2TIvbMF4QBLipsU",
	"NqI27YsARZO2+QJnxRefJev8FZbfqNhdPizJ5ZG8Oypnhe905HJ2dvY3szOzs6tD0La6tmVCE7mgeQjc",
	"9j7sqvTPDU27qzpIb+u2aqJt604fmmgLft6DLiLv4SO1axuQ/GlH7Vq6BporAxnYjmVDB+nQFbU4BHuW",
	"01URaALdRO+tAxmgAxuyn7ADHTAYyMCBn/d0B2qg+SBJYSf8wNr9FLYRGMjgfcNqf/YbQ8/kU3dbu6QN",
	"oYicHkyxyTc4DDrYtSwDqmaKI66xiBvGSIKDPd1xUctUu6Qt/haf4SG+BDKgUpMJyX2rCw3ouoxDGRhq",
	"+gM8wWdABl1d0wwoeonH3pdABva+hazgPf1x81O7A1LD3tUdtN/SVARjM0Me3EB6F0az4yJHNykFfiSH",
	"6dcdaGrQSU702qpgotnoCyBCzpmfhPwyGpjwofgdJ2nBgGLCFrznZZ16nUSOBmICjFPnOQk5FiLMgSqC",
	"0wCfBbfZQZXCTg4O5hFqQmqFBJYtp4+stop0yxRLStU0h6IGeCf44qaE/0WHPPROZem9XwEZBAKhz72n",
	"+JXkPfEe4yF+nZZJSEww5GJj9ccVEMoe1bbehfcMK2P+26qttnV0AJoriiIDaGq3qZKDVWX13RvK2o1V",
	"ZXvl101FaSrKH4kcfRltMnPkwHbPcaDZpsSgqW0zJqiloOTuq0YvoreepLdHxgTN9gFogocQfmYcEESb",
	"CDp91WDrhAudvt4mcntwSLTxM93sfKKbmvUQNNcUmRvCuhK2Jnz4PFL7FB/QrYCBgZxD8r00ydUMkms+",
	"yR0ZuEh1kECQt6KBIx0ZFC7/xSPvyDuW8BuKm2M88R7jEb7EYzyKTBwTdGBJYliKmC1kSsMpLmTHZfDo",
	"Rl81dGb6HxBvwNR0ggDQDEhJf+opyhqUolHLwOnR0QUtuj0XSbtQUvcQdLiGg51BHFOFjHwcdf/vwD3Q",
	"BP/XiByVhu+lNLailjEkHQIdwa6b93mgO/fYh4SGz43qOOoBpRlN9fwCDYkFIjWth5Ewo7eBOHVTQvtQ",
	"2uuhngMpmKdQa0vB1E+huAv3LAeGLen8+FAVmCr2gCh+r0uMkqubHYPSD+G6I+cYMkbdbxUDA6eHvJwj",
	"CHMzKrJ/dxzHcpL2ztJIo/sbH23e3tje/Pj3rTtbWx9vARloEKm6Qew7/h5P8AUeSe8QI/uOhCf4uXeK",
	"X+Khd4xH+MJ7RpY7Cb/AF96pRJ5T3b3Al0xvvVOy/EDXVTtUw7/zvsJj/Byf46FEF8sLPMYv8ND7Mx7j",
	"sUChKY8CcYcsihbKoL+8hYNSj9oLBddP+6WRlVlVZIrvyAiu+/ZN4Qy7HhlfToM2hb5/SQsWdV7UFS3s",
	"PiZMfaFvBEMsH7ykicTQHw45ySIdm2gOP4Roo6/qhrprQJ+ouwVd2zJdFpHFZqC0ZbwXcZG2iomxTVXS",
	"DyFi/mmMOx547C21lTnB0RxO644MbKo+KzKwodPyfygyQBainogS/E3fueRJGsgBrwWl6EeAgmXF9nW5",
	"gDpE7BZq7o+neNtgvAW+SJoaXxxBp/6wOJbjXWTgg5qjLHj4cn6wYAs1G7lVIbnVBaErhFQhbDEjfl2h",
	"xUQwJ7C47NUU21hGXhzBwhPFcSGcrqWdg9ho55yK/CWqHPqnrk+1DviCDzIeeamO773HeIxf45H3GF+y",
	"lMfK6lpkQ4Nl9e/4Ag/xGb6cI/1R2FcrkUnLTPzwuheXAZ/xzDL5lbkjMuhbRs9EEDrJNlKCUtQQdUS+",
	"dQWZ28IzNF++NCmCqU3I4Mt73WXSrLG+UtyJwLUVT45F2MrJk63PlieLz3vYRxSdm7APHT+YEMTlPBsZ",
	"SDF7Bg0ogq2HNHIiNqN+NVWn7IZ8dy0T7RsHQh6iMQkMYlc39S4hupI7tREnHE05FItovvg1I+FkMoXu",
	"6mbLho5uaS1NPXBjpu9b74hl8PAIv/Ce0RxIR3eRQw1sSw1isax9paI6leKh0EqTqUFZTObvbYV2Nc1T",
	"JlmR1IMcW2a+4d1kXjowxStKyplPpKeLp45Xc1LHIvMfuPphyDC1h7WcTDLXw5q4h3RiWcSVi1TUI2u3",
	"2kZ6H/Kp5h+8Yz+3fOmdeqeSd4QvvBP8E36Oh9w6wJJ4V5tnLrWs/JLyxYNoRiOLGk6t6rT39X5sf5nL",
	"zlaat6UGYL7kLRtXThY3KdOEm7ZYpU67T3H6hZBfUlEqT04WRZo4bRcmGrn5jEvF70U0eX+wSX9TCkPK",
	"ZVmuOnOczGcJErLZo75u28lsVL4abnELvHiAImeplEs0m6czs0MzlxPDZHM/iAnK1Vpcw4KKUBKVl5vI",
	"AHVaQSq30zKsjm6CJkDQRa0wRrtSGYYcFTPQIc95k8Gocl/Is84PXUvaPUdHB/eI58JE8j5UHehs9NA+",
	"Xfjorw+CAfz2k22yUNPWRIno22hA+wjZYDCg8dueRb7XoNt2dNvfit64uxnsl3on+A21Y2f4ItgvlfAZ",
	"dUxf+87pU/waj6l7iifeMbF5eCxL5Bc+Z/um3iltQlqd+G7sj6ydhM8kPMQvyN+U+hH1eofeMR7jM4qc",
	"VxJ+Q0E0whd4LN1TdRNJdzq6plucu8w/lja0rm5KG3c3SegPHZcNa+WmclMhs2jZ0FRtHTTBGn0kA1tF",
	"+1SsDW5TqAOpTSBADD1YbgeMfuaoXYigw2IWiuXPe9A5iFYEP7cXQYPF4swHZaLfU3sGoipRMoTO6DHK",
	"KGb3miK2Q1qzbC4d/KqisN1tE/nby6ptGzpbJBufuiwNGREs5HELtg/T25F065yHI/6BRusj7ys/VUlh",
	"doZH3jH5fL0kp1O3YWgRgoiH/LKAd6+Cj00TQcdUDYn4e9CRoN9QBm6v21Wdg7AiwjvxvgwqkyQqwLF3",
	"xNj/ieiW99R7IuFzOo4RvvSOfQuO1I7LbwfuEGtsuQJVuGu5nC44bBV939IOFiYGUUXkYMBMbQyrK4vr",
	"0t/krWE4Nwz/gyf4JWHOB6HvB0zwj3gSR95QiLuBHJrjxqGuDQrYZBr6JKwyfGQbtEZnTzVcKDObSQx+",
	"ZDLpSp1tLItEe+iA1Wjp1Hma25zWEP2ZLGUcl7TOU6L8sydj7ws8pm4NLf30TrIsZk9kMHvLidPFG27B",
	"0Q2h3a6VYgmV4m++6z72HlODfY6HDfxvPMQv8fP0q1kseYPP1eaa9KDaYElURn6rHP2w11VF1K36yO9W",
	"UXKYqHJFm1r+WKt05RFBFJWTuH9Cg/AT/IYINxEkZCx4RMFhPy9wZqWBb3XcvDB1yrQisWORpUxVFs1o",
	"5yakFWwl9ey21WUHHWzVRcJ9JDHRYPNocVwyvV8YvT3H6rb8ig0Buan7CGKKyJqRXsWmM1FxW9vL6u3l",
	"ET1l8pRmKV9xFtG3gbxBDH2d3BiWzWOw/i1NiFD7O7XSXj+lZZE9/fuNd8LvS4xz9DlQYw0akBWGxDX5",
	"Nn3O5vfa5KMSB5B67XbGmfxBev+qRva8yP6BZlEveFyHUPZOSyWpQkTLOevQLyKV6h+7qSFajfFdAEiz",
	"EqnLCNLF51EFFVmDeKWBX4xTa8jSa8h3+Lm/A7ZYQ55wTRrJY215Zv5u/GBYHXJc15BDeICy1uyryK5+",
	"iYfekXdM354TG5DQ/NnWviXU3IrWwamX1wl3FtcXE96E1ZCxI1TXMdpZV9aq5+MDy9nVNQ2ay6XA/yC6",
	"yBc5EhVOau1Qwudxtf06azkOkuNT19+PwkZXUXoXHh4e0CVpk33DbjKo6++utv6Oq4yNZY8j2Ewvuosj",
	"p6qyu+SJiEKBR5FCvDLnKnQNNNfyjlcUG1WkAQJ4/ZMvVmbZQB/xeMKUPqhkG9aYL1Xs9yqO93EG3mNm",
	"s2CONdSDOs06A6hPuKRiDepCedc4kkuF6wnbnuHZLymiq0pszbTELA4cs68I1F/kkzm1AhXOeS1IiciC",
	"UaSMMLt6sC47CpnIODwpODEUrUAVZ6vqOsCfsw6QU7rovH9M53LLWZaukGU2wKYvlsm6RKZwJBK77qxG",
	"dRWnOMb40vuCXs79OlppJvg5X+gxKrX2cGqQ7b8tJ+arct+m3C6wME+uVr+308mrVAHJOhTctsQ7fwkh",
	"fkNzEmf0PPlf8JDMYLTeTfB56iC79yQ6xs42aSSaw3iJX+MJ/omMktbGP/O+liinF94z/7x6kNtILYPb",
	"IZ/ZFoEpesna7WLXCgUGgdgOurFarNPwAqBypc6z9cddMjRXb1dyhj28Aa18Iv3j39UGZJZ8+XQt5UxE",
	"ZBOmJ9B5nawugZ78Xy4LS6AXYyICqgAe3/AipVnaQKTTkt81fMufcz9LSPpHJlP/rpQM8MYWuILZ8BDU",
	"dTZ8XshzqfEa8oUS4zOhPLsE+fphuQJLXUOzYDJgOjhLBSEJDyMjDbCk8F28oxNH7tXt3CzIt0lu49Qa",
	"VTi+X5Bb06BRrH/Brq2i9r5AochjTqU2gk8EquUni1bkepXIwvwQn/u36wW3eNSefQby/xqKKtgHXhzu",
	"WdKmDOz9L2p/qDDSvcfekxrphZAeimp+pIcXubJ/yJSZhbkftavGO4nuta340sBYR/V+QrX5FPrPOyfU",
	"Ux95j2NI5JCXhGLjkN7IO3XHOgLkdmdGzz249vetsbU1dKsOPpN4LRVvxhCdHXAuNXKr2n5OXeBe8RWD",
	"tapUH1UWNu7cregU4fx96A926H/foZ0z/Mf5uw370LDsLjSRzyKQQc8x/KvRmw1aiW7sWy5q3lJuKY3+",
	"ChjsDP4XAAD//4XC3vJdhQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
