// Code generated by my-super-puper-tool. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"errors"
	"github.com/google/uuid"
)

type TypeSet = interface {
	RequestID | UserID
}

func Parse[T TypeSet](s string) (T, error) {
	v, err := uuid.Parse(s)
	return T(v), err
}

func MustParse[T TypeSet](s string) T {
	return T(uuid.MustParse(s))
}

// RequestID type

type RequestID uuid.UUID

func NewRequestID() RequestID {
	return RequestID(uuid.New())
}

var RequestIDNil = RequestID(uuid.Nil)

func (t RequestID) String() string {
	return uuid.UUID(t).String()
}

func (t RequestID) Value() (driver.Value, error) {
	return t.String(), nil
}

func (t *RequestID) Scan(src any) error {
	return (*uuid.UUID)(t).Scan(src)
}

func (t RequestID) MarshalText() (text []byte, err error) {
	return uuid.UUID(t).MarshalText()
}

func (t *RequestID) UnmarshalText(text []byte) error {
	id, err := uuid.ParseBytes(text)
	if err != nil {
		return err
	}
	*t = RequestID(id)
	return nil
}

func (t RequestID) IsZero() bool {
	return t == RequestIDNil
}

func (t RequestID) Validate() error {
	if t.IsZero() {
		return errors.New("zero RequestID")
	}
	return nil
}

func (t *RequestID) Matches(x interface{}) bool {
	other, ok := x.(RequestID)
	if !ok {
		return false
	}
	return *t == other
}

// UserID type

type UserID uuid.UUID

func NewUserID() UserID {
	return UserID(uuid.New())
}

var UserIDNil = UserID(uuid.Nil)

func (t UserID) String() string {
	return uuid.UUID(t).String()
}

func (t UserID) Value() (driver.Value, error) {
	return t.String(), nil
}

func (t *UserID) Scan(src any) error {
	return (*uuid.UUID)(t).Scan(src)
}

func (t UserID) MarshalText() (text []byte, err error) {
	return uuid.UUID(t).MarshalText()
}

func (t *UserID) UnmarshalText(text []byte) error {
	id, err := uuid.ParseBytes(text)
	if err != nil {
		return err
	}
	*t = UserID(id)
	return nil
}

func (t UserID) IsZero() bool {
	return t == UserIDNil
}

func (t UserID) Validate() error {
	if t.IsZero() {
		return errors.New("zero UserID")
	}
	return nil
}

func (t *UserID) Matches(x interface{}) bool {
	other, ok := x.(UserID)
	if !ok {
		return false
	}
	return *t == other
}
