openapi: 3.0.3
info:
  title: SaintDiego CRM Client API
  version: v1

servers:
  - url: http://localhost:8080/v1
    description: Development server

paths:
  /testHandler:
    post:
      description: Initial handler for test purposes.
      parameters:
        - $ref: "#/components/parameters/XRequestIDHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHandlerRequest"
      responses:
        '200':
          description: Messages list.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestHandlerResponse"

security:
  - bearerAuth: [ ]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    XRequestIDHeader:
      in: header
      name: X-Request-ID
      schema:
        # https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#openapi-extensions
        type: string
        format: uuid
        x-go-type: types.RequestID
        x-go-type-import:
          path: "github.com/Slava02/SaintDiego/internal/types"
      required: true
      example: "151d6a6c-c716-43ab-93ff-bbd78d299027"

  schemas:
    TestHandlerRequest:
      properties:
        greeting:
          type: string

    TestHandlerResponse:
      required: [ answer ]
      properties:
        answer:
          type: string


