# https://taskfile.dev
version: "3"

silent: true

vars:
  GO_MODULE: github.com/Slava02/SaintDiego/backend/events
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "
  GO_CMD: ./cmd/main.go

  PROTO_PATH: api/events.proto
  PROTO_DST: pkg/pb

  GOLANGCI_LINT_VERSION: v1.62.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches"

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.13.5
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.33.1
    mvdan.cc/gofumpt@v0.7.0
    go.uber.org/mock/mockgen@v0.5.0

  DOCKER_COMPOSE_PATHS: |
    ./deploy/local/docker-compose.yml

  DOCKER_COMPOSE_CMD: docker compose -f {{ .DOCKER_COMPOSE_PATHS | trim | splitLines | join " -f " }}

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -w {{.GO_FILES}}
    - gci write -s standard -s default -s "prefix({{.GO_MODULE}})" --skip-generated {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: { CLI_ARGS: "run -v --fix --timeout=5m ./..." }

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build {{.GO_CMD}}

  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - |
        {{ range $tool := .DEV_TOOLS | trim | splitLines -}}
        go install {{ $tool }}
        {{ end }}

  generate:
    - echo "Run go generate..."
    - go generate ./...
    - task: gen:pb

  gen:pb:
    cmds:
      - protoc --proto_path=. --go_out={{.PROTO_DST}} --go_opt=paths=source_relative --go-grpc_out={{.PROTO_DST}} --go-grpc_opt=paths=source_relative {{.PROTO_PATH}}

  deps:
    cmds:
      - echo "- Starting dependencies"
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}} up -d"

  deps:cmd:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"

  deps:status:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} ps"

  deps:logs:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} logs {{.SERVICE}}"

  deps:stop:
    cmds:
      - echo "- Stopping running services"
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}} stop"

  deps:reset:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.SERVICE}}"
