// Code generated by options-gen. DO NOT EDIT.
package s

import (
	fmt461e464ebed9 "fmt"

	"github.com/Slava02/SaintDiego/backend/volunteers/internal/config"
	"github.com/Slava02/SaintDiego/backend/volunteers/pkg/pb"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"go.uber.org/zap"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	Lg *zap.Logger,
	ServerConfig *config.ServerConfig,
	VolunteersService pb.VolunteersServiceServer,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)
	o.Production = false

	o.Lg = Lg

	o.ServerConfig = ServerConfig

	o.VolunteersService = VolunteersService

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithProduction(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.Production = opt

	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("Lg", _validate_Options_Lg(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ServerConfig", _validate_Options_ServerConfig(o)))
	errs.Add(errors461e464ebed9.NewValidationError("VolunteersService", _validate_Options_VolunteersService(o)))
	return errs.AsError()
}

func _validate_Options_Lg(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Lg, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `Lg` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_ServerConfig(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServerConfig, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServerConfig` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_VolunteersService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.VolunteersService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `VolunteersService` did not pass the test: %w", err)
	}
	return nil
}
