services:
  api_gateway:
    container_name: api
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
      - events
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  schedule:
    container_name: schedule
    build:
      context: ./schedule
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50051:50051"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  services:
    container_name: services
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50052:50052"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  events:
    container_name: events
    build:
      context: ./events
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50053:50053"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50056:50056"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  clients:
    container_name: clients
    build:
      context: ./clients
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50055:50055"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  volunteers:
    container_name: volunteers
    build:
      context: ./volunteers
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: configs/config.docker.toml
    ports:
      - "50054:50054"
    depends_on:
      - jaeger
    restart: on-failure
    volumes:
      - go-mod-cache:/go/pkg/mod

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  go-mod-cache:


