syntax = "proto3";

package services;

option go_package = "github.com/Slava02/SaintDiego/backend/services/pkg/pb";

// Service definition
service ServicesService {

  // Services
  rpc GetServiceTypes(GetServiceTypesRequest) returns (GetServiceTypesResponse) {}
  rpc GetServiceTypeById(GetServiceTypeByIdRequest) returns (ServiceType) {}
  rpc UpdateServiceType(UpdateServiceTypeRequest) returns (ServiceType) {}
}

// Request messages
message GetServiceTypesRequest {
  optional bool registrationAvailable = 1;
}

message GetServiceTypeByIdRequest {
  int64 id = 1;
}

message UpdateServiceTypeRequest {
  int64 id = 1;
  int64 minPeriodDays = 2;
  bool registrationAvailable = 3;
}

// Response messages
message GetServiceTypesResponse {
  repeated ServiceType serviceTypes = 1;
}

// Common messages

message ServiceType {
  int64 id = 1;  
  string name = 2;
  int64 minPeriodDays = 3;
  bool registrationAvailable = 4;
}

message Error {
  string code = 1;
  string message = 2;
  map<string, string> details = 3;
}
