// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/pb/services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicesService_GetServiceTypes_FullMethodName    = "/services.ServicesService/GetServiceTypes"
	ServicesService_GetServiceTypeById_FullMethodName = "/services.ServicesService/GetServiceTypeById"
	ServicesService_UpdateServiceType_FullMethodName  = "/services.ServicesService/UpdateServiceType"
)

// ServicesServiceClient is the client API for ServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type ServicesServiceClient interface {
	// Services
	GetServiceTypes(ctx context.Context, in *GetServiceTypesRequest, opts ...grpc.CallOption) (*GetServiceTypesResponse, error)
	GetServiceTypeById(ctx context.Context, in *GetServiceTypeByIdRequest, opts ...grpc.CallOption) (*ServiceType, error)
	UpdateServiceType(ctx context.Context, in *UpdateServiceTypeRequest, opts ...grpc.CallOption) (*ServiceType, error)
}

type servicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesServiceClient(cc grpc.ClientConnInterface) ServicesServiceClient {
	return &servicesServiceClient{cc}
}

func (c *servicesServiceClient) GetServiceTypes(ctx context.Context, in *GetServiceTypesRequest, opts ...grpc.CallOption) (*GetServiceTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceTypesResponse)
	err := c.cc.Invoke(ctx, ServicesService_GetServiceTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) GetServiceTypeById(ctx context.Context, in *GetServiceTypeByIdRequest, opts ...grpc.CallOption) (*ServiceType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceType)
	err := c.cc.Invoke(ctx, ServicesService_GetServiceTypeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesServiceClient) UpdateServiceType(ctx context.Context, in *UpdateServiceTypeRequest, opts ...grpc.CallOption) (*ServiceType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceType)
	err := c.cc.Invoke(ctx, ServicesService_UpdateServiceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServiceServer is the server API for ServicesService service.
// All implementations must embed UnimplementedServicesServiceServer
// for forward compatibility.
//
// Service definition
type ServicesServiceServer interface {
	// Services
	GetServiceTypes(context.Context, *GetServiceTypesRequest) (*GetServiceTypesResponse, error)
	GetServiceTypeById(context.Context, *GetServiceTypeByIdRequest) (*ServiceType, error)
	UpdateServiceType(context.Context, *UpdateServiceTypeRequest) (*ServiceType, error)
	mustEmbedUnimplementedServicesServiceServer()
}

// UnimplementedServicesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicesServiceServer struct{}

func (UnimplementedServicesServiceServer) GetServiceTypes(context.Context, *GetServiceTypesRequest) (*GetServiceTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceTypes not implemented")
}
func (UnimplementedServicesServiceServer) GetServiceTypeById(context.Context, *GetServiceTypeByIdRequest) (*ServiceType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceTypeById not implemented")
}
func (UnimplementedServicesServiceServer) UpdateServiceType(context.Context, *UpdateServiceTypeRequest) (*ServiceType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServiceType not implemented")
}
func (UnimplementedServicesServiceServer) mustEmbedUnimplementedServicesServiceServer() {}
func (UnimplementedServicesServiceServer) testEmbeddedByValue()                         {}

// UnsafeServicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicesServiceServer will
// result in compilation errors.
type UnsafeServicesServiceServer interface {
	mustEmbedUnimplementedServicesServiceServer()
}

func RegisterServicesServiceServer(s grpc.ServiceRegistrar, srv ServicesServiceServer) {
	// If the following call pancis, it indicates UnimplementedServicesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicesService_ServiceDesc, srv)
}

func _ServicesService_GetServiceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetServiceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetServiceTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetServiceTypes(ctx, req.(*GetServiceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_GetServiceTypeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTypeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).GetServiceTypeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_GetServiceTypeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).GetServiceTypeById(ctx, req.(*GetServiceTypeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicesService_UpdateServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServiceServer).UpdateServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicesService_UpdateServiceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServiceServer).UpdateServiceType(ctx, req.(*UpdateServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicesService_ServiceDesc is the grpc.ServiceDesc for ServicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.ServicesService",
	HandlerType: (*ServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceTypes",
			Handler:    _ServicesService_GetServiceTypes_Handler,
		},
		{
			MethodName: "GetServiceTypeById",
			Handler:    _ServicesService_GetServiceTypeById_Handler,
		},
		{
			MethodName: "UpdateServiceType",
			Handler:    _ServicesService_UpdateServiceType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/services.proto",
}
