// Code generated by options-gen. DO NOT EDIT.
package volunteers_repo

import (
	fmt461e464ebed9 "fmt"

	"github.com/Slava02/SaintDiego/backend/common/storage"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	DB *storage.Database,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.DB = DB

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("DB", _validate_Options_DB(o)))
	return errs.AsError()
}

func _validate_Options_DB(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.DB, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `DB` did not pass the test: %w", err)
	}
	return nil
}
