// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptAuthClientOptionsSetter func(o *AuthClientOptions)

func NewAuthClientOptions(
	AuthServerAddr string,
	options ...OptAuthClientOptionsSetter,
) AuthClientOptions {
	o := AuthClientOptions{}

	// Setting defaults from field tag (if present)

	o.AuthServerAddr = AuthServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *AuthClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("AuthServerAddr", _validate_AuthClientOptions_AuthServerAddr(o)))
	return errs.AsError()
}

func _validate_AuthClientOptions_AuthServerAddr(o *AuthClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.AuthServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `AuthServerAddr` did not pass the test: %w", err)
	}
	return nil
}
