// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptEventsClientOptionsSetter func(o *EventsClientOptions)

func NewEventsClientOptions(
	EventsServerAddr string,
	options ...OptEventsClientOptionsSetter,
) EventsClientOptions {
	o := EventsClientOptions{}

	// Setting defaults from field tag (if present)

	o.EventsServerAddr = EventsServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *EventsClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("EventsServerAddr", _validate_EventsClientOptions_EventsServerAddr(o)))
	return errs.AsError()
}

func _validate_EventsClientOptions_EventsServerAddr(o *EventsClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.EventsServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `EventsServerAddr` did not pass the test: %w", err)
	}
	return nil
}
