// Code generated by options-gen. DO NOT EDIT.
package services

type OptEventsClientOptionsSetter func(o *EventsClientOptions)

func NewEventsClientOptions(
	options ...OptEventsClientOptionsSetter,
) EventsClientOptions {
	o := EventsClientOptions{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithServerAddr(opt string) OptEventsClientOptionsSetter {
	return func(o *EventsClientOptions) {
		o.ServerAddr = opt

	}
}

func (o *EventsClientOptions) Validate() error {
	return nil
}
