// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptManagerOptionsSetter func(o *ManagerOptions)

func NewManagerOptions(
	EventsAddr string,
	options ...OptManagerOptionsSetter,
) ManagerOptions {
	o := ManagerOptions{}

	// Setting defaults from field tag (if present)

	o.EventsAddr = EventsAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ManagerOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("EventsAddr", _validate_ManagerOptions_EventsAddr(o)))
	return errs.AsError()
}

func _validate_ManagerOptions_EventsAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.EventsAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `EventsAddr` did not pass the test: %w", err)
	}
	return nil
}
