// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptManagerOptionsSetter func(o *ManagerOptions)

func NewManagerOptions(
	ScheduleAddr string,
	ServicesAddr string,
	EventsAddr string,
	VolunteersAddr string,
	ClientsAddr string,
	options ...OptManagerOptionsSetter,
) ManagerOptions {
	o := ManagerOptions{}

	// Setting defaults from field tag (if present)

	o.ScheduleAddr = ScheduleAddr

	o.ServicesAddr = ServicesAddr

	o.EventsAddr = EventsAddr

	o.VolunteersAddr = VolunteersAddr

	o.ClientsAddr = ClientsAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ManagerOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ScheduleAddr", _validate_ManagerOptions_ScheduleAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ServicesAddr", _validate_ManagerOptions_ServicesAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("EventsAddr", _validate_ManagerOptions_EventsAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("VolunteersAddr", _validate_ManagerOptions_VolunteersAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ClientsAddr", _validate_ManagerOptions_ClientsAddr(o)))
	return errs.AsError()
}

func _validate_ManagerOptions_ScheduleAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ScheduleAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ScheduleAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_ServicesAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_EventsAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.EventsAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `EventsAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_VolunteersAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.VolunteersAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `VolunteersAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_ClientsAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ClientsAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ClientsAddr` did not pass the test: %w", err)
	}
	return nil
}
