// Code generated by options-gen. DO NOT EDIT.
package services

type OptScheduleClientOptionsSetter func(o *ScheduleClientOptions)

func NewScheduleClientOptions(
	options ...OptScheduleClientOptionsSetter,
) ScheduleClientOptions {
	o := ScheduleClientOptions{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithServerAddr(opt string) OptScheduleClientOptionsSetter {
	return func(o *ScheduleClientOptions) {
		o.ServerAddr = opt

	}
}

func (o *ScheduleClientOptions) Validate() error {
	return nil
}
