// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptScheduleClientOptionsSetter func(o *ScheduleClientOptions)

func NewScheduleClientOptions(
	ScheduleServerAddr string,
	options ...OptScheduleClientOptionsSetter,
) ScheduleClientOptions {
	o := ScheduleClientOptions{}

	// Setting defaults from field tag (if present)

	o.ScheduleServerAddr = ScheduleServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ScheduleClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ScheduleServerAddr", _validate_ScheduleClientOptions_ScheduleServerAddr(o)))
	return errs.AsError()
}

func _validate_ScheduleClientOptions_ScheduleServerAddr(o *ScheduleClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ScheduleServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ScheduleServerAddr` did not pass the test: %w", err)
	}
	return nil
}
