// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptServicesClientOptionsSetter func(o *ServicesClientOptions)

func NewServicesClientOptions(
	ServicesServerAddr string,
	options ...OptServicesClientOptionsSetter,
) ServicesClientOptions {
	o := ServicesClientOptions{}

	// Setting defaults from field tag (if present)

	o.ServicesServerAddr = ServicesServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ServicesClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ServicesServerAddr", _validate_ServicesClientOptions_ServicesServerAddr(o)))
	return errs.AsError()
}

func _validate_ServicesClientOptions_ServicesServerAddr(o *ServicesClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesServerAddr` did not pass the test: %w", err)
	}
	return nil
}
