// Code generated by options-gen. DO NOT EDIT.
package services

type OptServicesClientOptionsSetter func(o *ServicesClientOptions)

func NewServicesClientOptions(
	options ...OptServicesClientOptionsSetter,
) ServicesClientOptions {
	o := ServicesClientOptions{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithServicesServerAddr(opt string) OptServicesClientOptionsSetter {
	return func(o *ServicesClientOptions) {
		o.ServicesServerAddr = opt

	}
}

func (o *ServicesClientOptions) Validate() error {
	return nil
}
