// Code generated by options-gen. DO NOT EDIT.
package services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptVolunteersClientOptionsSetter func(o *VolunteersClientOptions)

func NewVolunteersClientOptions(
	VolunteersServerAddr string,
	options ...OptVolunteersClientOptionsSetter,
) VolunteersClientOptions {
	o := VolunteersClientOptions{}

	// Setting defaults from field tag (if present)

	o.VolunteersServerAddr = VolunteersServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *VolunteersClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("VolunteersServerAddr", _validate_VolunteersClientOptions_VolunteersServerAddr(o)))
	return errs.AsError()
}

func _validate_VolunteersClientOptions_VolunteersServerAddr(o *VolunteersClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.VolunteersServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `VolunteersServerAddr` did not pass the test: %w", err)
	}
	return nil
}
