syntax = "proto3";

package events;

option go_package = "github.com/Slava02/SaintDiego/backend/events/pkg/pb";

import "google/protobuf/timestamp.proto";

// Service definition
service EventsService {

  // Services
  rpc GetEvents(GetEventsRequest) returns (GetEventsResponse) {}
  rpc GetEventById(GetEventByIdRequest) returns (Event) {}
  rpc UpdateEvent(UpdateEventRequest) returns (Event) {}
  rpc DeleteEvent(DeleteEventRequest) returns (DeleteEventResponse) {}
  rpc AddParticipantToEvent(AddParticipantToEventRequest) returns (AddParticipantToEventResponse) {}
  rpc GetParticipantsByEventId(GetParticipantsByEventIdRequest) returns (GetParticipantsByEventIdResponse) {}
  rpc GetEventsByServiceId(GetEventsByServiceIdRequest) returns (GetEventsByServiceIdResponse) {}
}

// Request messages
message GetEventsByServiceIdRequest {
  int64 service_id = 1;
  int64 page = 2;
  int64 per_page = 3;
}

message GetEventsRequest {
  optional int64 participant_id = 1;
  optional string status = 2;
  optional int64 location_id = 3;
  optional int64 service_id = 4;
  optional google.protobuf.Timestamp from_date = 5;
  optional google.protobuf.Timestamp to_date = 6;
  int64 page = 7;
  int64 per_page = 8;
}

message GetEventByIdRequest {
  int64 id = 1;
}

message UpdateEventRequest {
  int64 id = 1;
  int32 capacity = 2;
  google.protobuf.Timestamp datetime = 3;
}

message DeleteEventRequest {
  int64 id = 1;
}

message AddParticipantToEventRequest {
  int64 event_id = 1;
  int64 participant_id = 2;
  int64 volunteer_id = 3;
}

message GetParticipantsByEventIdRequest {
  int64 event_id = 1;
  int64 page = 2;
  int64 per_page = 3;
}

// Response messages
// TODO: тут не обязательно возвращать page, per_page, т.к. они уже есть в запросе (см. GetServicesResponse)
message GetEventsResponse {
  repeated Event events = 1;
  int64 total = 2;
}

message DeleteEventResponse {
  bool success = 1;
}

message AddParticipantToEventResponse {
  bool success = 1;
}

message GetParticipantsByEventIdResponse {
  repeated Participant participants = 1;
  int64 total = 2;
}

message GetEventsByServiceIdResponse {
  repeated Event events = 1;
  int64 total = 2;
}

// Common messages
message Event {
  int64 id = 1;
  int64 timeSlotServiceId = 2;
  int64 serviceTypeId = 3;
  int32 capacity = 4;
  google.protobuf.Timestamp datetime = 5;
}

message Participant {
  int64 id = 1;
  string first_name = 2;
  string middle_name = 3;
  string last_name = 4;
  string photo_name = 5;
  google.protobuf.Timestamp birth_date = 6;
  int64 gender = 7;
  bool is_homeless = 8;
  int64 volunteer_tg = 9;
  string volunteer_tg_login = 10;
}
