// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Slava02/SaintDiego/backend/schedule/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ITimeSlotsRepository is an autogenerated mock type for the ITimeSlotsRepository type
type ITimeSlotsRepository struct {
	mock.Mock
}

// ActivateTimeSlot provides a mock function with given fields: ctx, id
func (_m *ITimeSlotsRepository) ActivateTimeSlot(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateTimeSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArchiveTimeSlot provides a mock function with given fields: ctx, id
func (_m *ITimeSlotsRepository) ArchiveTimeSlot(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveTimeSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTimeSlotServices provides a mock function with given fields: ctx, id, req
func (_m *ITimeSlotsRepository) CreateTimeSlotServices(ctx context.Context, id int64, req []*models.TimeSlotService) ([]*models.TimeSlotService, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTimeSlotServices")
	}

	var r0 []*models.TimeSlotService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []*models.TimeSlotService) ([]*models.TimeSlotService, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []*models.TimeSlotService) []*models.TimeSlotService); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TimeSlotService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []*models.TimeSlotService) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEventsByServiceIds provides a mock function with given fields: ctx, serviceIds
func (_m *ITimeSlotsRepository) DeleteEventsByServiceIds(ctx context.Context, serviceIds []int64) error {
	ret := _m.Called(ctx, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEventsByServiceIds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, serviceIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTimeSlot provides a mock function with given fields: ctx, id
func (_m *ITimeSlotsRepository) DeleteTimeSlot(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTimeSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTimeSlotRecurrence provides a mock function with given fields: ctx, timeSlotID
func (_m *ITimeSlotsRepository) DeleteTimeSlotRecurrence(ctx context.Context, timeSlotID int64) error {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTimeSlotRecurrence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTimeSlotServicesByIds provides a mock function with given fields: ctx, serviceIds
func (_m *ITimeSlotsRepository) DeleteTimeSlotServicesByIds(ctx context.Context, serviceIds []int64) error {
	ret := _m.Called(ctx, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTimeSlotServicesByIds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, serviceIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrentEvents provides a mock function with given fields: ctx
func (_m *ITimeSlotsRepository) GetCurrentEvents(ctx context.Context) ([]*models.Event, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentEvents")
	}

	var r0 []*models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByServiceIds provides a mock function with given fields: ctx, serviceIds
func (_m *ITimeSlotsRepository) GetEventsByServiceIds(ctx context.Context, serviceIds []int64) ([]*models.Event, error) {
	ret := _m.Called(ctx, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByServiceIds")
	}

	var r0 []*models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*models.Event, error)); ok {
		return rf(ctx, serviceIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*models.Event); ok {
		r0 = rf(ctx, serviceIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, serviceIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPastEvents provides a mock function with given fields: ctx
func (_m *ITimeSlotsRepository) GetPastEvents(ctx context.Context) ([]*models.Event, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPastEvents")
	}

	var r0 []*models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeSlot provides a mock function with given fields: ctx, id
func (_m *ITimeSlotsRepository) GetTimeSlot(ctx context.Context, id int64) (*models.TimeSlot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeSlot")
	}

	var r0 *models.TimeSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.TimeSlot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.TimeSlot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TimeSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeSlots provides a mock function with given fields: ctx, status, startDate, endDate
func (_m *ITimeSlotsRepository) GetTimeSlots(ctx context.Context, status string, startDate time.Time, endDate time.Time) ([]*models.TimeSlot, error) {
	ret := _m.Called(ctx, status, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeSlots")
	}

	var r0 []*models.TimeSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*models.TimeSlot, error)); ok {
		return rf(ctx, status, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*models.TimeSlot); ok {
		r0 = rf(ctx, status, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TimeSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, status, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUpdateEvents provides a mock function with given fields: ctx, events
func (_m *ITimeSlotsRepository) InsertUpdateEvents(ctx context.Context, events []*models.Event) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for InsertUpdateEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Event) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertUpdateTimeSlot provides a mock function with given fields: ctx, req
func (_m *ITimeSlotsRepository) InsertUpdateTimeSlot(ctx context.Context, req *models.TimeSlot) (*models.TimeSlot, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertUpdateTimeSlot")
	}

	var r0 *models.TimeSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TimeSlot) (*models.TimeSlot, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TimeSlot) *models.TimeSlot); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TimeSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TimeSlot) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITimeSlotsRepository creates a new instance of ITimeSlotsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITimeSlotsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITimeSlotsRepository {
	mock := &ITimeSlotsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
