package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Transactor is an autogenerated mock type for the Transactor type
type Transactor struct {
	mock.Mock
}

// WithinTransaction provides a mock function with given fields: ctx, tFunc
func (t *Transactor) WithinTransaction(ctx context.Context, tFunc func(context.Context) error) error {
	ret := t.Called(ctx, tFunc)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	return tFunc(ctx)
}

// NewTransactor creates a new instance of Transactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactor {
	mock := &Transactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
