// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/pb/schedule.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduleService_GetTimeSlot_FullMethodName      = "/schedule.ScheduleService/GetTimeSlot"
	ScheduleService_GetTimeSlots_FullMethodName     = "/schedule.ScheduleService/GetTimeSlots"
	ScheduleService_CreateTimeSlot_FullMethodName   = "/schedule.ScheduleService/CreateTimeSlot"
	ScheduleService_UpdateTimeSlot_FullMethodName   = "/schedule.ScheduleService/UpdateTimeSlot"
	ScheduleService_DeleteTimeSlot_FullMethodName   = "/schedule.ScheduleService/DeleteTimeSlot"
	ScheduleService_ArchiveTimeSlot_FullMethodName  = "/schedule.ScheduleService/ArchiveTimeSlot"
	ScheduleService_ActivateTimeSlot_FullMethodName = "/schedule.ScheduleService/ActivateTimeSlot"
	ScheduleService_GetLocations_FullMethodName     = "/schedule.ScheduleService/GetLocations"
	ScheduleService_CreateLocation_FullMethodName   = "/schedule.ScheduleService/CreateLocation"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type ScheduleServiceClient interface {
	// Time slots
	GetTimeSlot(ctx context.Context, in *GetTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error)
	GetTimeSlots(ctx context.Context, in *GetTimeSlotsRequest, opts ...grpc.CallOption) (*GetTimeSlotsResponse, error)
	CreateTimeSlot(ctx context.Context, in *CreateTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error)
	UpdateTimeSlot(ctx context.Context, in *TimeSlot, opts ...grpc.CallOption) (*TimeSlot, error)
	DeleteTimeSlot(ctx context.Context, in *DeleteTimeSlotRequest, opts ...grpc.CallOption) (*DeleteTimeSlotResponse, error)
	ArchiveTimeSlot(ctx context.Context, in *ArchiveTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error)
	ActivateTimeSlot(ctx context.Context, in *ActivateTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error)
	// Locations
	GetLocations(ctx context.Context, in *GetLocationsRequest, opts ...grpc.CallOption) (*GetLocationsResponse, error)
	CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*Location, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) GetTimeSlot(ctx context.Context, in *GetTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlot)
	err := c.cc.Invoke(ctx, ScheduleService_GetTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetTimeSlots(ctx context.Context, in *GetTimeSlotsRequest, opts ...grpc.CallOption) (*GetTimeSlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeSlotsResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetTimeSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) CreateTimeSlot(ctx context.Context, in *CreateTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlot)
	err := c.cc.Invoke(ctx, ScheduleService_CreateTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) UpdateTimeSlot(ctx context.Context, in *TimeSlot, opts ...grpc.CallOption) (*TimeSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlot)
	err := c.cc.Invoke(ctx, ScheduleService_UpdateTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) DeleteTimeSlot(ctx context.Context, in *DeleteTimeSlotRequest, opts ...grpc.CallOption) (*DeleteTimeSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTimeSlotResponse)
	err := c.cc.Invoke(ctx, ScheduleService_DeleteTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) ArchiveTimeSlot(ctx context.Context, in *ArchiveTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlot)
	err := c.cc.Invoke(ctx, ScheduleService_ArchiveTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) ActivateTimeSlot(ctx context.Context, in *ActivateTimeSlotRequest, opts ...grpc.CallOption) (*TimeSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlot)
	err := c.cc.Invoke(ctx, ScheduleService_ActivateTimeSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetLocations(ctx context.Context, in *GetLocationsRequest, opts ...grpc.CallOption) (*GetLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocationsResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Location)
	err := c.cc.Invoke(ctx, ScheduleService_CreateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility.
//
// Service definition
type ScheduleServiceServer interface {
	// Time slots
	GetTimeSlot(context.Context, *GetTimeSlotRequest) (*TimeSlot, error)
	GetTimeSlots(context.Context, *GetTimeSlotsRequest) (*GetTimeSlotsResponse, error)
	CreateTimeSlot(context.Context, *CreateTimeSlotRequest) (*TimeSlot, error)
	UpdateTimeSlot(context.Context, *TimeSlot) (*TimeSlot, error)
	DeleteTimeSlot(context.Context, *DeleteTimeSlotRequest) (*DeleteTimeSlotResponse, error)
	ArchiveTimeSlot(context.Context, *ArchiveTimeSlotRequest) (*TimeSlot, error)
	ActivateTimeSlot(context.Context, *ActivateTimeSlotRequest) (*TimeSlot, error)
	// Locations
	GetLocations(context.Context, *GetLocationsRequest) (*GetLocationsResponse, error)
	CreateLocation(context.Context, *CreateLocationRequest) (*Location, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleServiceServer struct{}

func (UnimplementedScheduleServiceServer) GetTimeSlot(context.Context, *GetTimeSlotRequest) (*TimeSlot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) GetTimeSlots(context.Context, *GetTimeSlotsRequest) (*GetTimeSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSlots not implemented")
}
func (UnimplementedScheduleServiceServer) CreateTimeSlot(context.Context, *CreateTimeSlotRequest) (*TimeSlot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) UpdateTimeSlot(context.Context, *TimeSlot) (*TimeSlot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) DeleteTimeSlot(context.Context, *DeleteTimeSlotRequest) (*DeleteTimeSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) ArchiveTimeSlot(context.Context, *ArchiveTimeSlotRequest) (*TimeSlot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) ActivateTimeSlot(context.Context, *ActivateTimeSlotRequest) (*TimeSlot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateTimeSlot not implemented")
}
func (UnimplementedScheduleServiceServer) GetLocations(context.Context, *GetLocationsRequest) (*GetLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocations not implemented")
}
func (UnimplementedScheduleServiceServer) CreateLocation(context.Context, *CreateLocationRequest) (*Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocation not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}
func (UnimplementedScheduleServiceServer) testEmbeddedByValue()                         {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	// If the following call pancis, it indicates UnimplementedScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_GetTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetTimeSlot(ctx, req.(*GetTimeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetTimeSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetTimeSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetTimeSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetTimeSlots(ctx, req.(*GetTimeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_CreateTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTimeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).CreateTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_CreateTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).CreateTimeSlot(ctx, req.(*CreateTimeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_UpdateTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeSlot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).UpdateTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_UpdateTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).UpdateTimeSlot(ctx, req.(*TimeSlot))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_DeleteTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTimeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).DeleteTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_DeleteTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).DeleteTimeSlot(ctx, req.(*DeleteTimeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_ArchiveTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTimeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).ArchiveTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_ArchiveTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).ArchiveTimeSlot(ctx, req.(*ArchiveTimeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_ActivateTimeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateTimeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).ActivateTimeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_ActivateTimeSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).ActivateTimeSlot(ctx, req.(*ActivateTimeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetLocations(ctx, req.(*GetLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_CreateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).CreateLocation(ctx, req.(*CreateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeSlot",
			Handler:    _ScheduleService_GetTimeSlot_Handler,
		},
		{
			MethodName: "GetTimeSlots",
			Handler:    _ScheduleService_GetTimeSlots_Handler,
		},
		{
			MethodName: "CreateTimeSlot",
			Handler:    _ScheduleService_CreateTimeSlot_Handler,
		},
		{
			MethodName: "UpdateTimeSlot",
			Handler:    _ScheduleService_UpdateTimeSlot_Handler,
		},
		{
			MethodName: "DeleteTimeSlot",
			Handler:    _ScheduleService_DeleteTimeSlot_Handler,
		},
		{
			MethodName: "ArchiveTimeSlot",
			Handler:    _ScheduleService_ArchiveTimeSlot_Handler,
		},
		{
			MethodName: "ActivateTimeSlot",
			Handler:    _ScheduleService_ActivateTimeSlot_Handler,
		},
		{
			MethodName: "GetLocations",
			Handler:    _ScheduleService_GetLocations_Handler,
		},
		{
			MethodName: "CreateLocation",
			Handler:    _ScheduleService_CreateLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/schedule.proto",
}
