[global]
name = "api-gateway"
env = "dev"

[log]
level = "debug"

[servers.apiGW]
addr = "0.0.0.0:8080"

[services.schedule]
addr = "localhost:50051"

[services.services]
addr = "localhost:50052"

[services.events]
addr = "localhost:50053"

[services.volunteers]
addr = "localhost:50054"

[services.clients]
addr = "localhost:50055"

[services.auth]
addr = "localhost:50056"

[servers.apiGW.jwt]
secret = "secret"
