[global]
name = "api-gateway"
env = "dev"

[log]
level = "info"

[servers.apiGW]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]

[services.events]
addr = ":5001"

[services.schedule]
addr = ":5002"

[services.services]
addr = ":5003"

[services.volunteers]
addr = ":50054"

[services.clients]
addr = ":50055"
