[global]
name = "events"
env = "dev"

[log]
level = "info"

[server]
addr = ":50053"
max_connection_idle = 10
timeout = 10
max_connection_age = 10
time = 10


[database]
host = "33"
db_name = "33"
password = "33"
user = "33"
port = "33"

[grpc_client]
[grpc_client.services]
addr = ":50052"

[grpc_client.volunteers]
addr = ":50054"

[grpc_client.clients]
addr = ":50055"

[grpc_client.locations]
addr = ":50051"
