[global]
name = "events"
env = "dev"

[log]
level = "debug"

[server]
addr = ":50053"
max_connection_idle = 10
timeout = 10
max_connection_age = 10
time = 10

[database]
host = "mks-db"
db_name = "homeless"
password = "12345ghJkbn"
user = "homeless"
port = "3306"

[grpc_client]
[grpc_client.services]
addr = "services:50052"

[grpc_client.volunteers]
addr = "volunteers:50054"

[grpc_client.clients]
addr = "clients:50055"
