name: SaintDiego
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command:
      - start-dev --import-realm
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/saintDiego-realm.json
#    volumes:
#      - ./saintDiego-realm.json:/opt/keycloak/data/import/saintDiego-realm.json
    ports:
      - "127.0.0.1:3010:8080"


