// Code generated by options-gen. DO NOT EDIT.
package timeSlots

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	TimeSlotsRepository ITimeSlotsRepository,
	Transactor Transactor,
	ServicesClient IServicesClient,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.TimeSlotsRepository = TimeSlotsRepository

	o.Transactor = Transactor

	o.ServicesClient = ServicesClient

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("TimeSlotsRepository", _validate_Options_TimeSlotsRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("Transactor", _validate_Options_Transactor(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ServicesClient", _validate_Options_ServicesClient(o)))
	return errs.AsError()
}

func _validate_Options_TimeSlotsRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.TimeSlotsRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `TimeSlotsRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_Transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `Transactor` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_ServicesClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesClient` did not pass the test: %w", err)
	}
	return nil
}
