// Code generated by options-gen. DO NOT EDIT.
package events

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	EventRepository IEventRepository,
	Transactor Transactor,
	ServicesClient IServicesClient,
	ClientsClient IClientsClient,
	VolunteersClient IVolunteersClient,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.EventRepository = EventRepository

	o.Transactor = Transactor

	o.ServicesClient = ServicesClient

	o.ClientsClient = ClientsClient

	o.VolunteersClient = VolunteersClient

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("EventRepository", _validate_Options_EventRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("Transactor", _validate_Options_Transactor(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ServicesClient", _validate_Options_ServicesClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ClientsClient", _validate_Options_ClientsClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("VolunteersClient", _validate_Options_VolunteersClient(o)))
	return errs.AsError()
}

func _validate_Options_EventRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.EventRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `EventRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_Transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `Transactor` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_ServicesClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_ClientsClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ClientsClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ClientsClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_VolunteersClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.VolunteersClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `VolunteersClient` did not pass the test: %w", err)
	}
	return nil
}
