services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: saint_egidio_bot:latest
    container_name: saint_egidio_bot
    restart: unless-stopped
    env_file:
      - path: ./docker.env
        required: true
    working_dir: /app
    volumes:
      - ./:/app:ro
    networks:
      - saint_egidio_network
    command: ["python3", "-u", "main.py"]

networks:
  saint_egidio_network:
    external: true
    name: saint_egidio_network
