type: object
properties:
  id:
    type: integer
    format: int64
  serviceTypeId:
    type: integer
    format: int64
  periodDays:
    type: integer
    format: int32
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
required:
  - serviceTypeId
  - periodDays
example:
  id: 1
  serviceTypeId: 1
  periodDays: 30
  createdAt: '2024-03-20T09:00:00Z'
  updatedAt: '2024-03-20T09:00:00Z'
