openapi: 3.0.0
info:
  title: Saint Egidio Admin API
  description: >-
    API для управления временными слотами, локациями и услугами в
    административной панели Saint Egidio
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Development server
  - url: http://host.docker.internal:8080/v1
    description: Docker-окружение
security:
  - BearerAuth: []
paths:
  /locations:
    $ref: paths/locations.yml
  /locations/{id}:
    $ref: paths/locations_{id}.yml
  /services:
    $ref: paths/services.yml
  /services/{id}:
    $ref: paths/services_{id}.yml
  /timeSlots:
    $ref: paths/timeSlots.yml
  /timeSlots/{id}:
    $ref: paths/timeSlots_{id}.yml
  /timeSlots/{id}/activate:
    $ref: paths/timeSlots_{id}_activate.yml
  /timeSlots/{id}/archive:
    $ref: paths/timeSlots_{id}_archive.yml
  /events:
    $ref: paths/events.yml
  /events/{id}:
    $ref: paths/events_{id}.yml
  /events/{id}/participants:
    $ref: paths/events_{id}_participants.yml
  /events/{id}/participants/{participant_id}:
    $ref: paths/events_{id}_participants_{participant_id}.yml
  /events/services/{id}:
    $ref: paths/events_services_{id}.yml
  /clients:
    $ref: paths/clients.yml
  /clients/{id}:
    $ref: paths/clients_{id}.yml
  /clients/{id}/events:
    $ref: paths/clients_{id}_events.yml
  /clients/{id}/services:
    $ref: paths/clients_{id}_services.yml
  /clients/{id}/services/{service_id}/events:
    $ref: paths/clients_{id}_services_{service_id}_events.yml
  /volunteers:
    $ref: paths/volunteers.yml
  /volunteers/{tg_id}:
    $ref: paths/volunteers_{tg_id}.yml
  /login:
    $ref: paths/login.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
