// Code generated by options-gen. DO NOT EDIT.
package grpc_services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptClientsClientOptionsSetter func(o *ClientsClientOptions)

func NewClientsClientOptions(
	ClientsServerAddr string,
	options ...OptClientsClientOptionsSetter,
) ClientsClientOptions {
	o := ClientsClientOptions{}

	// Setting defaults from field tag (if present)

	o.ClientsServerAddr = ClientsServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ClientsClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ClientsServerAddr", _validate_ClientsClientOptions_ClientsServerAddr(o)))
	return errs.AsError()
}

func _validate_ClientsClientOptions_ClientsServerAddr(o *ClientsClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ClientsServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ClientsServerAddr` did not pass the test: %w", err)
	}
	return nil
}
