// Code generated by options-gen. DO NOT EDIT.
package grpc_services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptLocationsClientOptionsSetter func(o *LocationsClientOptions)

func NewLocationsClientOptions(
	LocationsServerAddr string,
	options ...OptLocationsClientOptionsSetter,
) LocationsClientOptions {
	o := LocationsClientOptions{}

	// Setting defaults from field tag (if present)

	o.LocationsServerAddr = LocationsServerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *LocationsClientOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("LocationsServerAddr", _validate_LocationsClientOptions_LocationsServerAddr(o)))
	return errs.AsError()
}

func _validate_LocationsClientOptions_LocationsServerAddr(o *LocationsClientOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.LocationsServerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `LocationsServerAddr` did not pass the test: %w", err)
	}
	return nil
}
