// Code generated by options-gen. DO NOT EDIT.
package grpc_services

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptManagerOptionsSetter func(o *ManagerOptions)

func NewManagerOptions(
	ServicesAddr string,
	ClientAddr string,
	VolunteerAddr string,
	options ...OptManagerOptionsSetter,
) ManagerOptions {
	o := ManagerOptions{}

	// Setting defaults from field tag (if present)

	o.ServicesAddr = ServicesAddr

	o.ClientAddr = ClientAddr

	o.VolunteerAddr = VolunteerAddr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *ManagerOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ServicesAddr", _validate_ManagerOptions_ServicesAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ClientAddr", _validate_ManagerOptions_ClientAddr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("VolunteerAddr", _validate_ManagerOptions_VolunteerAddr(o)))
	return errs.AsError()
}

func _validate_ManagerOptions_ServicesAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_ClientAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ClientAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ClientAddr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ManagerOptions_VolunteerAddr(o *ManagerOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.VolunteerAddr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `VolunteerAddr` did not pass the test: %w", err)
	}
	return nil
}
