get:
  tags:
    - services
  summary: Получение списка услуг
  parameters:
    - name: page
      in: query
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    - name: per_page
      in: query
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
    - name: registration_available
      in: query
      required: false
      schema:
        type: boolean
  responses:
    '200':
      description: Успешный ответ
      content:
        application/json:
          schema:
            $ref: ../components/schemas/GetServicesResponse.yml
    '400':
      description: Ошибка валидации
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yml
