// Code generated by options-gen. DO NOT EDIT.
package auth

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	AuthRepository IAuthRepository,
	Secret string,
	TokenTTL time.Duration,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.AuthRepository = AuthRepository

	o.Secret = Secret

	o.TokenTTL = TokenTTL

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("AuthRepository", _validate_Options_AuthRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("Secret", _validate_Options_Secret(o)))
	errs.Add(errors461e464ebed9.NewValidationError("TokenTTL", _validate_Options_TokenTTL(o)))
	return errs.AsError()
}

func _validate_Options_AuthRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.AuthRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `AuthRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_Secret(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Secret, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `Secret` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_TokenTTL(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.TokenTTL, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `TokenTTL` did not pass the test: %w", err)
	}
	return nil
}
