// Code generated by options-gen. DO NOT EDIT.
package storage

import (
	"database/sql"
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	SqlDB *sql.DB,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.SqlDB = SqlDB

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithProd(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.Prod = opt

	}
}

func WithModels(opt []any) OptOptionsSetter {
	return func(o *Options) {
		o.Models = opt

	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("SqlDB", _validate_Options_SqlDB(o)))
	errs.Add(errors461e464ebed9.NewValidationError("Prod", _validate_Options_Prod(o)))
	errs.Add(errors461e464ebed9.NewValidationError("Models", _validate_Options_Models(o)))
	return errs.AsError()
}

func _validate_Options_SqlDB(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.SqlDB, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `SqlDB` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_Prod(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Prod, "omitempty"); err != nil {
		return fmt461e464ebed9.Errorf("field `Prod` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_Models(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Models, "omitempty"); err != nil {
		return fmt461e464ebed9.Errorf("field `Models` did not pass the test: %w", err)
	}
	return nil
}
