// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/pb/volunteers.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolunteersService_CreateVolunteer_FullMethodName    = "/volunteers.VolunteersService/CreateVolunteer"
	VolunteersService_GetVolunteerByTgId_FullMethodName = "/volunteers.VolunteersService/GetVolunteerByTgId"
	VolunteersService_UpdateVolunteer_FullMethodName    = "/volunteers.VolunteersService/UpdateVolunteer"
)

// VolunteersServiceClient is the client API for VolunteersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type VolunteersServiceClient interface {
	CreateVolunteer(ctx context.Context, in *CreateVolunteerRequest, opts ...grpc.CallOption) (*Volunteer, error)
	GetVolunteerByTgId(ctx context.Context, in *GetVolunteerByTgIdRequest, opts ...grpc.CallOption) (*Volunteer, error)
	UpdateVolunteer(ctx context.Context, in *UpdateVolunteerRequest, opts ...grpc.CallOption) (*Volunteer, error)
}

type volunteersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolunteersServiceClient(cc grpc.ClientConnInterface) VolunteersServiceClient {
	return &volunteersServiceClient{cc}
}

func (c *volunteersServiceClient) CreateVolunteer(ctx context.Context, in *CreateVolunteerRequest, opts ...grpc.CallOption) (*Volunteer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volunteer)
	err := c.cc.Invoke(ctx, VolunteersService_CreateVolunteer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteersServiceClient) GetVolunteerByTgId(ctx context.Context, in *GetVolunteerByTgIdRequest, opts ...grpc.CallOption) (*Volunteer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volunteer)
	err := c.cc.Invoke(ctx, VolunteersService_GetVolunteerByTgId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteersServiceClient) UpdateVolunteer(ctx context.Context, in *UpdateVolunteerRequest, opts ...grpc.CallOption) (*Volunteer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volunteer)
	err := c.cc.Invoke(ctx, VolunteersService_UpdateVolunteer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolunteersServiceServer is the server API for VolunteersService service.
// All implementations must embed UnimplementedVolunteersServiceServer
// for forward compatibility.
//
// Service definition
type VolunteersServiceServer interface {
	CreateVolunteer(context.Context, *CreateVolunteerRequest) (*Volunteer, error)
	GetVolunteerByTgId(context.Context, *GetVolunteerByTgIdRequest) (*Volunteer, error)
	UpdateVolunteer(context.Context, *UpdateVolunteerRequest) (*Volunteer, error)
	mustEmbedUnimplementedVolunteersServiceServer()
}

// UnimplementedVolunteersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolunteersServiceServer struct{}

func (UnimplementedVolunteersServiceServer) CreateVolunteer(context.Context, *CreateVolunteerRequest) (*Volunteer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolunteer not implemented")
}
func (UnimplementedVolunteersServiceServer) GetVolunteerByTgId(context.Context, *GetVolunteerByTgIdRequest) (*Volunteer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolunteerByTgId not implemented")
}
func (UnimplementedVolunteersServiceServer) UpdateVolunteer(context.Context, *UpdateVolunteerRequest) (*Volunteer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVolunteer not implemented")
}
func (UnimplementedVolunteersServiceServer) mustEmbedUnimplementedVolunteersServiceServer() {}
func (UnimplementedVolunteersServiceServer) testEmbeddedByValue()                           {}

// UnsafeVolunteersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolunteersServiceServer will
// result in compilation errors.
type UnsafeVolunteersServiceServer interface {
	mustEmbedUnimplementedVolunteersServiceServer()
}

func RegisterVolunteersServiceServer(s grpc.ServiceRegistrar, srv VolunteersServiceServer) {
	// If the following call pancis, it indicates UnimplementedVolunteersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolunteersService_ServiceDesc, srv)
}

func _VolunteersService_CreateVolunteer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolunteerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteersServiceServer).CreateVolunteer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteersService_CreateVolunteer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteersServiceServer).CreateVolunteer(ctx, req.(*CreateVolunteerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteersService_GetVolunteerByTgId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolunteerByTgIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteersServiceServer).GetVolunteerByTgId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteersService_GetVolunteerByTgId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteersServiceServer).GetVolunteerByTgId(ctx, req.(*GetVolunteerByTgIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteersService_UpdateVolunteer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVolunteerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteersServiceServer).UpdateVolunteer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteersService_UpdateVolunteer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteersServiceServer).UpdateVolunteer(ctx, req.(*UpdateVolunteerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolunteersService_ServiceDesc is the grpc.ServiceDesc for VolunteersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolunteersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "volunteers.VolunteersService",
	HandlerType: (*VolunteersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolunteer",
			Handler:    _VolunteersService_CreateVolunteer_Handler,
		},
		{
			MethodName: "GetVolunteerByTgId",
			Handler:    _VolunteersService_GetVolunteerByTgId_Handler,
		},
		{
			MethodName: "UpdateVolunteer",
			Handler:    _VolunteersService_UpdateVolunteer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/volunteers.proto",
}
