// Code generated by options-gen. DO NOT EDIT.
package clients

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	ClientsRepository IClientsRepository,
	ServicesClient IServicesClient,
	EventsClient IEventsClient,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.ClientsRepository = ClientsRepository

	o.ServicesClient = ServicesClient

	o.EventsClient = EventsClient

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("ClientsRepository", _validate_Options_ClientsRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("ServicesClient", _validate_Options_ServicesClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("EventsClient", _validate_Options_EventsClient(o)))
	return errs.AsError()
}

func _validate_Options_ClientsRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ClientsRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ClientsRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_ServicesClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.ServicesClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `ServicesClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_EventsClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.EventsClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `EventsClient` did not pass the test: %w", err)
	}
	return nil
}
